//! `streamOgToAnthropic`'s STATE MACHINE — the streaming half of the gateway's translation.
//!
//! WHAT MOVED AND WHAT DID NOT. The TypeScript function is a `ReadableStream` transformer: it owns a
//! reader, a `TextDecoder`, a byte buffer and the SSE frame splitting. THAT HALF STAYS IN
//! `gateway/src/anthropic-translate.ts` — it is I/O, and it is the same boundary the non-streaming
//! move drew (the plan's P3 rule: I/O outside, the derivation pure). What is here is the derivation:
//! `AnthropicStreamEncoder`, 385 lines of state machine that turn parsed OpenAI chunks into Anthropic
//! SSE events.
//!
//! EVERY RULE IN HERE IS A DEFECT THAT SHIPPED, and the comments say which round found it — the
//! usage-only final chunk dropped by a choices guard, the error frame swallowed mid-stream, the
//! first chunk emitted twice, the tool_use named "unknown" whose late id never arrived, the
//! duplicate `content_block_stop` that strict clients read as a corrupted stream, the unterminated
//! final text block. A port that "cleaned these up" would be a port that reintroduced them.
//!
//! # WHAT PROVES IT
//!
//! `fixtures/stream-corpus.json` holds chunk sequences and the SSE TEXT THE TYPESCRIPT PRODUCED for
//! them — generated by the shipping class, not by this one — and `tests::the_typescript_corpus`
//! replays every case here and compares byte for byte. It runs in the `gateway` job's
//! `cargo test --manifest-path gateway/wasm/Cargo.toml`, so the equivalence is re-checked on every
//! push rather than recorded once in a commit message.
//!
//! # THE ONE BOUNDARY, STATED RATHER THAN HIDDEN
//!
//! `toolBlockIdxMap` and `toolMeta` are JavaScript `Record<number, T>`s, and JS orders such an
//! object's keys by CANONICAL ARRAY INDEX ASCENDING FIRST, then everything else in insertion order
//! (`Object.keys({10:1,2:1,b:1,a:1})` is `["2","10","b","a"]`). The order is observable: `finish()`
//! emits delayed `content_block_start`s and the closing `content_block_stop`s in it. `JsMap` below
//! reproduces exactly that, keyed by `ToString(value)` as JS property keys are — so a fractional or
//! string index is a different key here for the same reason it is one there.

use serde_json::{json, Map, Value};
use std::collections::HashSet;

use crate::translate::{sse, truthy_js};

/// `STREAM_STOP_MAP` — the four OpenAI finish reasons the Anthropic vocabulary knows.
const STREAM_STOP_MAP: [(&str, &str); 4] = [
    ("stop", "end_turn"),
    ("tool_calls", "tool_use"),
    ("function_call", "tool_use"),
    ("length", "max_tokens"),
];

/// `String(v)` as a TEMPLATE LITERAL coerces — which is not `Array.prototype.join`'s rule: `${null}`
/// is `"null"` where `[null].join("")` is `""`, and `${[1,2]}` is `"1,2"` where serde would print
/// `[1,2]`.
pub fn js_text(v: &Value) -> String {
    match v {
        Value::Null => "null".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => s.clone(),
        Value::Array(items) => items
            .iter()
            .map(|i| match i {
                Value::Null => String::new(),
                other => js_text(other),
            })
            .collect::<Vec<_>>()
            .join(","),
        // `String({})` is `"[object Object]"`, and so is every plain object's.
        Value::Object(_) => "[object Object]".to_string(),
    }
}

/// `a || b` — `a` when it is truthy, `b` otherwise.
fn or(a: &Value, b: Value) -> Value {
    if truthy_js(a) {
        a.clone()
    } else {
        b
    }
}

/// `a ?? b` — `a` unless it is null or undefined.
fn nullish_or(a: Option<&Value>, b: Value) -> Value {
    match a {
        None | Some(Value::Null) => b,
        Some(v) => v.clone(),
    }
}

/// `v?.k` — a property read that a nullish receiver answers `undefined` for.
fn opt_prop(v: Option<&Value>, key: &str) -> Option<Value> {
    match v {
        Some(Value::Object(o)) => o.get(key).cloned(),
        _ => None,
    }
}

/// `v.k`, where a NON-OBJECT receiver answers `undefined` (JavaScript boxes a primitive and finds no
/// such property) — the same rule `field()` in the console's crate records.
fn prop(v: &Value, key: &str) -> Option<Value> {
    match v {
        Value::Object(o) => o.get(key).cloned(),
        _ => None,
    }
}

/// A `Record<string, T>` with JAVASCRIPT'S KEY ORDER — see the module header.
#[derive(Default)]
struct JsMap<T> {
    entries: Vec<(String, T)>,
}

impl<T> JsMap<T> {
    fn get(&self, key: &str) -> Option<&T> {
        self.entries.iter().find(|(k, _)| k == key).map(|(_, v)| v)
    }
    fn get_mut(&mut self, key: &str) -> Option<&mut T> {
        self.entries
            .iter_mut()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v)
    }
    fn set(&mut self, key: &str, value: T) {
        match self.get_mut(key) {
            Some(slot) => *slot = value,
            None => self.entries.push((key.to_string(), value)),
        }
    }
    fn contains(&self, key: &str) -> bool {
        self.get(key).is_some()
    }
    /// `Object.entries` — canonical array indices ascending, then insertion order.
    fn keys_in_js_order(&self) -> Vec<String> {
        let index_of = |k: &str| -> Option<u64> {
            if k.is_empty() || (k.len() > 1 && k.starts_with('0')) {
                return None;
            }
            let n: u64 = k.parse().ok()?;
            // A canonical array index is a string whose numeric value round-trips and is below 2^32-1.
            if n < u32::MAX as u64 && n.to_string() == k {
                Some(n)
            } else {
                None
            }
        };
        let mut indices: Vec<(u64, String)> = Vec::new();
        let mut others: Vec<String> = Vec::new();
        for (k, _) in &self.entries {
            match index_of(k) {
                Some(n) => indices.push((n, k.clone())),
                None => others.push(k.clone()),
            }
        }
        indices.sort_by_key(|(n, _)| *n);
        let mut out: Vec<String> = indices.into_iter().map(|(_, k)| k).collect();
        out.extend(others);
        out
    }
}

/// One tool's real id and name, however late they arrived.
#[derive(Clone, Default)]
struct ToolMeta {
    id: Value,
    name: Value,
}

pub struct AnthropicStreamEncoder {
    /// ASSIGNED AND NEVER READ, exactly as in the TypeScript (the wire carries `upstreamModel`); it
    /// is kept because a caller constructs the encoder with both names and a port that dropped one
    /// would be a different constructor.
    #[allow(dead_code)]
    client_model: String,
    upstream_model: String,
    started: bool,
    finished: bool,
    block_index: i64,
    /// `"thinking" | "text" | "tool_use" | null`
    block_type: Option<&'static str>,
    tool_idx: Option<i64>,
    next_tool_block_idx: i64,
    tool_block_idx_map: JsMap<i64>,
    tool_meta: JsMap<ToolMeta>,
    started_blocks: HashSet<i64>,
    open_tool_inputs: JsMap<String>,
    stopped_tool_blocks: HashSet<i64>,
    pending: Vec<String>,
    last_stop_reason: String,
    id: Value,
    usage_input_tokens: Value,
    usage_output_tokens: Value,
    usage_cache_creation_input_tokens: Value,
    usage_cache_read_input_tokens: Value,
}

impl AnthropicStreamEncoder {
    pub fn new(client_model: &str, upstream_model: &str) -> Self {
        AnthropicStreamEncoder {
            client_model: client_model.to_string(),
            upstream_model: upstream_model.to_string(),
            started: false,
            finished: false,
            block_index: -1,
            block_type: None,
            tool_idx: None,
            next_tool_block_idx: 0,
            tool_block_idx_map: JsMap::default(),
            tool_meta: JsMap::default(),
            started_blocks: HashSet::new(),
            open_tool_inputs: JsMap::default(),
            stopped_tool_blocks: HashSet::new(),
            pending: Vec::new(),
            last_stop_reason: "end_turn".to_string(),
            id: Value::String(String::new()),
            usage_input_tokens: json!(0),
            usage_output_tokens: json!(0),
            usage_cache_creation_input_tokens: json!(0),
            usage_cache_read_input_tokens: json!(0),
        }
    }

    pub fn started(&self) -> bool {
        self.started
    }

    pub fn finished(&self) -> bool {
        self.finished
    }

    fn usage(&self) -> Value {
        let mut m = Map::new();
        m.insert("input_tokens".into(), self.usage_input_tokens.clone());
        m.insert("output_tokens".into(), self.usage_output_tokens.clone());
        m.insert(
            "cache_creation_input_tokens".into(),
            self.usage_cache_creation_input_tokens.clone(),
        );
        m.insert(
            "cache_read_input_tokens".into(),
            self.usage_cache_read_input_tokens.clone(),
        );
        Value::Object(m)
    }

    /// `push(chunk)` — one parsed OpenAI `chat.completion.chunk`.
    ///
    /// `Err` mirrors the one input the TypeScript RAISES on: `for (const tc of delta.tool_calls)`
    /// throws on a value that is not iterable, and a port that quietly ignored it would answer a
    /// different stream where the JavaScript answers an exception.
    pub fn push(&mut self, chunk: &Value) -> Result<(), String> {
        if self.finished {
            return Ok(());
        }
        // `chunk.usage` ON A NULLISH CHUNK IS A TypeError, and the corpus carries the case (a null in
        // the chunk list): a port that read `undefined` there would translate a stream the JavaScript
        // refuses to touch. A NUMBER or a STRING is fine — `(5).usage` is `undefined` — so only the two
        // nullish values raise, which is the same rule `require_present` states in the panel's crate.
        if chunk.is_null() {
            return Err(
                "chunk is null: the TypeScript raises on a property read from it".to_string(),
            );
        }
        // round-116: capture usage BEFORE the choice guard — OpenAI streams end with a usage-only
        // chunk (`{choices:[], usage:{...}}`) that the old `if (!choice) return` dropped entirely, so
        // the client never received input/cache token counts (message_start fired with zeros).
        if let Some(usage) = prop(chunk, "usage").filter(truthy_js) {
            self.usage_input_tokens = or(
                &prop(&usage, "prompt_tokens").unwrap_or(Value::Null),
                json!(0),
            );
            self.usage_output_tokens = or(
                &prop(&usage, "completion_tokens").unwrap_or(Value::Null),
                json!(0),
            );
            // zen reports cache hits as `usage.prompt_tokens_details.cached_tokens` — read both
            // names, same as `toAnthropicResponse`.
            let hit = prop(&usage, "prompt_cache_hit_tokens").unwrap_or(Value::Null);
            let details = opt_prop(Some(&usage), "prompt_tokens_details");
            let cached = opt_prop(details.as_ref(), "cached_tokens").unwrap_or(Value::Null);
            self.usage_cache_read_input_tokens = or(&hit, cached);
            self.usage_cache_read_input_tokens =
                or(&self.usage_cache_read_input_tokens.clone(), json!(0));
        }
        // round-123/124: a mid-stream upstream error frame (OpenAI shape `{"error":{...}}`) was
        // silently dropped by the choices guard below — the client got a complete-looking TRUNCATED
        // answer with no error, no retry, and the breaker never learned. Surface it as a TERMINAL
        // error event: the error frame ends the stream (no message_delta/message_stop after it, no
        // further chunks translated), and the done-branch's empty-stream check is skipped (`started`
        // is set so it will not double-fire with a misleading second error).
        if let Some(err) = prop(chunk, "error").filter(truthy_js) {
            let msg = or(
                &prop(&err, "message").unwrap_or(Value::Null),
                Value::String("upstream stream error".into()),
            );
            let frame = json!({
                "type": "error",
                "error": {
                    "type": "api_error",
                    "message": format!("upstream mid-stream error: {}", js_text(&msg)),
                },
            });
            self.pending.push(sse("error", &frame));
            self.started = true; // suppress the done-branch empty-stream error
            self.finished = true;
            return Ok(());
        }
        let choices = prop(chunk, "choices");
        let choice = choices
            .as_ref()
            .and_then(|c| c.as_array())
            .and_then(|a| a.first())
            .cloned();
        let Some(choice) = choice else {
            return Ok(());
        };
        let delta = prop(&choice, "delta")
            .filter(truthy_js)
            .unwrap_or_else(|| json!({}));
        if !truthy_js(&self.id) {
            if let Some(id) = prop(chunk, "id") {
                self.id = id;
            }
        }
        if let Some(reason) = prop(&choice, "finish_reason").filter(truthy_js) {
            let key = js_text(&reason);
            self.last_stop_reason = STREAM_STOP_MAP
                .iter()
                .find(|(k, _)| *k == key)
                .map(|(_, v)| (*v).to_string())
                .unwrap_or_else(|| "end_turn".to_string());
        }

        if let Some(rc) = prop(&delta, "reasoning_content").filter(truthy_js) {
            self.ensure_block("thinking", &json!({ "thinking": rc, "signature": "" }));
        }
        // Command Code streams reasoning in `delta.reasoning` (OpenAI-format backend), sometimes as a
        // reasoner-chunk list in `reasoning_details`.
        if let Some(r) = prop(&delta, "reasoning").filter(truthy_js) {
            let thinking = match &r {
                Value::Array(items) => Value::String(
                    items
                        .iter()
                        .map(|i| match i {
                            Value::Null => String::new(),
                            other => js_text(other),
                        })
                        .collect::<Vec<_>>()
                        .join(""),
                ),
                other => other.clone(),
            };
            self.ensure_block(
                "thinking",
                &json!({ "thinking": thinking, "signature": "" }),
            );
        }
        if let Some(content) = prop(&delta, "content").filter(truthy_js) {
            self.ensure_block("text", &json!({ "text": content }));
        }
        let tool_calls = prop(&delta, "tool_calls").unwrap_or(Value::Null);
        for tc in iterable(&tool_calls)? {
            let idx = nullish_or(prop(&tc, "index").as_ref(), json!(0));
            let function = prop(&tc, "function")
                .filter(truthy_js)
                .unwrap_or_else(|| json!({}));
            let id = prop(&tc, "id").unwrap_or(Value::Null);
            let name = prop(&function, "name").unwrap_or(Value::Null);
            let args = prop(&function, "arguments").unwrap_or(Value::Null);
            let args = or(&args, Value::String(String::new()));
            self.ensure_tool_block(&idx, id, name, args);
        }
        Ok(())
    }

    /// `finish(tailBuffer)` — close every open block and append `message_delta` + `message_stop`.
    /// Call once on stream end; `None` when the encoder was already finished.
    pub fn finish(&mut self, tail_buffer: &str) -> Option<String> {
        if self.finished {
            return None;
        }
        if !tail_buffer.trim().is_empty() {
            // A trailing partial event (no blank line yet) — best-effort parse. Must run BEFORE
            // `finished = true`: `push` early-returns once finished, so the old order made this parse
            // dead code and dropped the tail frame.
            let data_line = tail_buffer.split('\n').find(|l| l.starts_with("data:"));
            if let Some(line) = data_line {
                let payload = line[5..].trim();
                if !payload.is_empty() && payload != "[DONE]" {
                    if let Ok(parsed) = serde_json::from_str::<Value>(payload) {
                        let _ = self.push(&parsed); // a malformed JSON frame is ignored
                    }
                }
            }
        }
        self.finished = true;
        // The client expects `message_start` to be the first event.
        if !self.started {
            self.emit_start();
        }
        // round-116: emit any DELAYED `content_block_start` (the new-tool branch waits for the
        // id/name chunk; a stream that ended before it arrived would otherwise close a block that was
        // never opened — protocol error).
        for key in self.tool_block_idx_map.keys_in_js_order() {
            let Some(bi) = self.tool_block_idx_map.get(&key).copied() else {
                continue;
            };
            let meta = self.tool_meta.get(&key).cloned();
            let Some(meta) = meta else { continue };
            if self.stopped_tool_blocks.contains(&bi) || self.started_blocks.contains(&bi) {
                continue;
            }
            self.pending.push(sse(
                "content_block_start",
                &json!({
                    "type": "content_block_start",
                    "index": bi,
                    "content_block": {
                        "type": "tool_use",
                        "id": or(&meta.id, Value::String(String::new())),
                        "name": or(&meta.name, Value::String("unknown".into())),
                        "input": {},
                    },
                }),
            ));
        }
        // Close EVERY still-open tool block (parallel calls leave several open). round-96: skip
        // blocks already stopped by a type-switch (they would get a duplicate `content_block_stop` —
        // the round-95 bug).
        let mut seen: Vec<i64> = Vec::new();
        for key in self.tool_block_idx_map.keys_in_js_order() {
            let Some(bi) = self.tool_block_idx_map.get(&key).copied() else {
                continue;
            };
            if seen.contains(&bi) || self.stopped_tool_blocks.contains(&bi) {
                continue;
            }
            seen.push(bi);
            self.pending.push(sse(
                "content_block_stop",
                &json!({ "type": "content_block_stop", "index": bi }),
            ));
        }
        // round-68: close the open TEXT/THINKING block before resetting — the old order reset
        // `blockIndex` to -1 first, so the final text block never got `content_block_stop` (every
        // plain chat reply ended with an unterminated block; strict clients read it as truncated).
        if self.block_type.is_some() && self.block_type != Some("tool_use") {
            self.close_block();
        }
        self.tool_block_idx_map = JsMap::default();
        self.block_index = -1;
        self.block_type = None;
        self.pending.push(sse(
            "message_delta",
            &json!({
                "type": "message_delta",
                "delta": { "stop_reason": self.last_stop_reason, "stop_sequence": Value::Null },
                // round-116: the old delta carried ONLY `output_tokens` — input and cache-read were
                // dropped, so the client's cache-hit tracking read 0% and its usage accounting was
                // wrong (the non-stream path delivers all three).
                "usage": self.usage(),
            }),
        ));
        self.pending
            .push(sse("message_stop", &json!({ "type": "message_stop" })));
        Some(self.take())
    }

    /// Drain queued Anthropic SSE text.
    pub fn take(&mut self) -> String {
        if self.pending.is_empty() {
            return String::new();
        }
        let out = self.pending.join("");
        self.pending.clear();
        out
    }

    fn emit_start(&mut self) {
        if self.started {
            return;
        }
        self.started = true;
        self.pending.push(sse(
            "message_start",
            &json!({
                "type": "message_start",
                "message": {
                    "id": self.id,
                    "type": "message",
                    "role": "assistant",
                    "model": self.upstream_model,
                    "content": [],
                    "stop_reason": Value::Null,
                    "stop_sequence": Value::Null,
                    "usage": self.usage(),
                },
            }),
        ));
    }

    /// Push a `content_block_delta` for the CURRENT `block_index`. Shared by `ensure_block`'s
    /// first-chunk and continuation paths — the thinking/text delta arms used to be copy-pasted
    /// between them.
    fn push_content_delta(&mut self, delta: Value) {
        self.pending.push(sse(
            "content_block_delta",
            &json!({ "type": "content_block_delta", "index": self.block_index, "delta": delta }),
        ));
    }

    fn ensure_block(&mut self, kind: &'static str, block: &Value) {
        if !self.started {
            self.emit_start();
        }
        if self.block_type != Some(kind) {
            self.close_block();
            // Shared index counter — tool blocks allocate from the same sequence so text/thinking and
            // tool blocks never collide on an index.
            self.block_index = self.next_tool_block_idx;
            self.next_tool_block_idx += 1;
            self.block_type = Some(kind);
            // round-96: `content_block_start` must hold the block's INITIAL state, not the first
            // chunk — the same chunk was also emitted as the first delta below, so clients got the
            // first chunk twice (the Anthropic SDK seeds the block from start, then appends deltas).
            let content_block = match kind {
                // round-97: keep the `signature` field (empty) — strict client parsers hard-fail on
                // its absence (claude-agent-sdk-python KeyError 'signature'; anthropic-sdk-csharp
                // threw on eager access).
                "thinking" => json!({ "type": "thinking", "thinking": "", "signature": "" }),
                "text" => json!({ "type": "text", "text": "" }),
                _ => json!({
                    "type": "tool_use",
                    "id": or(&prop(block, "id").unwrap_or(Value::Null), Value::String(String::new())),
                    "name": or(
                        &prop(block, "name").unwrap_or(Value::Null),
                        Value::String("unknown".into()),
                    ),
                    "input": {},
                }),
            };
            self.pending.push(sse(
                "content_block_start",
                &json!({
                    "type": "content_block_start",
                    "index": self.block_index,
                    "content_block": content_block,
                }),
            ));
        }
        let delta = if kind == "thinking" {
            json!({ "type": "thinking_delta", "thinking": prop(block, "thinking").unwrap_or(Value::Null) })
        } else {
            json!({ "type": "text_delta", "text": prop(block, "text").unwrap_or(Value::Null) })
        };
        self.push_content_delta(delta);
    }

    fn ensure_tool_block(&mut self, idx: &Value, id: Value, name: Value, args_delta: Value) {
        if !self.started {
            self.emit_start();
        }
        let key = js_text(idx);
        // PARALLEL tool calls: OpenAI streams multiple tools with increasing indices (each new tool's
        // first chunk carries its id/name). Each tool gets its OWN content block, indexed by its tool
        // index (a running counter re-emitted duplicate indices on interleaved 0,1,0,1 streams —
        // round-19). text/thinking blocks stay on the running `blockIndex` and close before a tool
        // block opens.
        if self.block_type.is_some() && self.block_type != Some("tool_use") {
            self.close_block();
        }
        // round-116: track the tool's real id/name on the map — an upstream (or the exit proxy) can
        // stream `{index, function:{arguments}}` FIRST and the id/name on a LATER chunk. The old code
        // emitted `content_block_start` with `id:""`/`name:"unknown"` on that first chunk and then
        // DROPPED the late id (the map-hit branch ignored it) / stored the name in a write-only field
        // — the client saw a `tool_use` named "unknown" with an empty id and could never match the
        // `tool_result` round-trip. The start is now DELAYED until a chunk carries the id or name (or
        // until `finish()`).
        let has_block = self.tool_block_idx_map.contains(&key);
        if has_block && (truthy_js(&id) || truthy_js(&name)) {
            let prev = self.tool_meta.get(&key).cloned().unwrap_or_default();
            self.tool_meta.set(
                &key,
                ToolMeta {
                    id: if truthy_js(&id) { id.clone() } else { prev.id },
                    name: if truthy_js(&name) {
                        name.clone()
                    } else {
                        prev.name
                    },
                },
            );
        }
        // If this tool already has a block, route to it (interleaved streams return to tool 0 after
        // tool 1 started) — never re-open.
        if let Some(bi) = self.tool_block_idx_map.get(&key).copied() {
            self.block_index = bi;
            // round-97: resuming a block that was stopped by a type-switch re-opens it — it MUST be
            // re-stopped at `finish()`. Remove it from `stoppedToolBlocks` so `finish()`'s loop emits
            // `content_block_stop` again (the mirror of the R96 fix: the old code kept it stopped, so
            // the resumed block never got its stop and the `tool_use` was unterminated at
            // `message_stop`).
            self.stopped_tool_blocks.remove(&bi);
            self.block_type = Some("tool_use");
            if truthy_js(&args_delta) {
                let cur = self.open_tool_inputs.get(&key).cloned().unwrap_or_default();
                self.open_tool_inputs
                    .set(&key, format!("{cur}{}", js_text(&args_delta)));
                self.pending.push(sse(
                    "content_block_delta",
                    &json!({
                        "type": "content_block_delta",
                        "index": self.block_index,
                        "delta": { "type": "input_json_delta", "partial_json": args_delta },
                    }),
                ));
            }
            return;
        }
        // A NEW tool index ALWAYS opens a fresh block — even if the current block is another
        // `tool_use` (interleaved streams switch tools).
        if self.block_type.is_some() && self.block_type != Some("tool_use") {
            self.close_block();
        }
        self.tool_idx = idx.as_i64();
        // Track this tool's dedicated block index (may interleave with text).
        let tool_block_idx = self.next_tool_block_idx;
        self.next_tool_block_idx += 1;
        self.tool_block_idx_map.set(&key, tool_block_idx);
        self.block_index = tool_block_idx;
        self.block_type = Some("tool_use");
        if truthy_js(&id) || truthy_js(&name) {
            let prev = self.tool_meta.get(&key).cloned().unwrap_or_default();
            self.tool_meta.set(
                &key,
                ToolMeta {
                    id: if truthy_js(&id) {
                        id.clone()
                    } else {
                        Value::String(String::new())
                    },
                    name: if truthy_js(&name) {
                        name.clone()
                    } else {
                        prev.name
                    },
                },
            );
        }
        // round-116: delay `content_block_start` until the id or name is known — an upstream
        // streaming `{index, arguments}` first would otherwise lock the block to `id:""`/
        // `name:"unknown"` forever (the map-hit branch dropped the late id). The args accumulate in
        // `openToolInputs` meanwhile; the start (with the real id/name) is emitted on the first chunk
        // that carries them, or at `finish()` with whatever arrived.
        let have_meta = truthy_js(&id)
            || truthy_js(&name)
            || self
                .tool_meta
                .get(&key)
                .map(|m| truthy_js(&m.name))
                .unwrap_or(false);
        if have_meta {
            let m = self.tool_meta.get(&key).cloned().unwrap_or_default();
            self.pending.push(sse(
                "content_block_start",
                &json!({
                    "type": "content_block_start",
                    "index": self.block_index,
                    "content_block": {
                        "type": "tool_use",
                        "id": or(&m.id, or(&id, Value::String(String::new()))),
                        "name": or(&m.name, or(&name, Value::String("unknown".into()))),
                        "input": {},
                    },
                }),
            ));
            self.started_blocks.insert(self.block_index);
        }
        if truthy_js(&args_delta) {
            let cur = self.open_tool_inputs.get(&key).cloned().unwrap_or_default();
            self.open_tool_inputs
                .set(&key, format!("{cur}{}", js_text(&args_delta)));
            // Route the delta to THIS tool's block index (interleaved streams).
            let delta_idx = self
                .tool_block_idx_map
                .get(&key)
                .copied()
                .unwrap_or(self.block_index);
            self.pending.push(sse(
                "content_block_delta",
                &json!({
                    "type": "content_block_delta",
                    "index": delta_idx,
                    "delta": { "type": "input_json_delta", "partial_json": args_delta },
                }),
            ));
        }
    }

    fn close_block(&mut self) {
        if self.block_index >= 0 {
            self.pending.push(sse(
                "content_block_stop",
                &json!({ "type": "content_block_stop", "index": self.block_index }),
            ));
            // round-95: a block closed here (type switch mid-stream) must not be stopped AGAIN by
            // `finish()`'s `toolBlockIdxMap` loop — that emitted a duplicate `content_block_stop` for
            // an already-stopped index (protocol violation strict clients read as a corrupted
            // stream). round-96: record the stopped index instead of deleting the map entry — an
            // interleaved upstream stream can resume this tool's `input_json_delta` after the text
            // block, and deleting the entry made the resume open a bogus second `tool_use` block
            // (name "unknown").
            if self.block_type == Some("tool_use") {
                self.stopped_tool_blocks.insert(self.block_index);
            }
            self.block_index = -1;
            self.block_type = None;
        }
    }
}

/// `for (const x of v)` — an ARRAY's elements, a STRING's characters, and an `Err` for anything else
/// that is truthy (which is what the TypeScript raises on: `5 is not iterable`). A falsy value is the
/// empty list, because `delta.tool_calls || []` is what the loop is written over.
fn iterable(v: &Value) -> Result<Vec<Value>, String> {
    match v {
        Value::Null => Ok(Vec::new()),
        Value::Bool(false) => Ok(Vec::new()),
        Value::Number(n) if n.as_f64() == Some(0.0) => Ok(Vec::new()),
        Value::String(s) if s.is_empty() => Ok(Vec::new()),
        Value::Array(items) => Ok(items.clone()),
        Value::String(s) => Ok(s.chars().map(|c| Value::String(c.to_string())).collect()),
        other => Err(format!("tool_calls is not iterable: {}", js_text(other))),
    }
}

/// **THE SSE FRAME READER — the pure half of `streamOgToAnthropic`, which is the streaming path's whole
/// decision.**
///
/// The source's `parseBuffered` is five rules, and every one of them is a place a plausible port goes wrong:
///
/// ```js
/// while ((idx = buffer.indexOf("\n\n")) !== -1) {
///   const raw = buffer.slice(0, idx); buffer = buffer.slice(idx + 2);
///   const dataLine = raw.split("\n").find((l) => l.startsWith("data:"));
///   if (!dataLine) continue;
///   const payload = dataLine.slice(5).trim();
///   if (payload === "[DONE]") continue;
///   try { encoderStream.push(JSON.parse(payload)); } catch { /* malformed */ }
/// }
/// ```
///
///   * **THE BUFFER SURVIVES A PARTIAL FRAME.** A chunk that ends mid-frame keeps its bytes for the next one,
///     which is why this is a struct and not a function;
///   * **THE SEPARATOR IS `\n\n`** — not `\r\n\r\n`, so a CRLF stream would not split here at all;
///   * **THE FIRST `data:` LINE WINS** (`find`, not `filter`/last) and it does not need a space after the
///     colon; `slice(5)` removes `data:` and `trim()` takes the rest;
///   * **`[DONE]` IS SKIPPED**, not passed to the encoder;
///   * **A MALFORMED FRAME IS SWALLOWED** — and that happens in the CALLER, because the parse is where the
///     failure is: this returns the payload STRINGS and the caller parses each one, dropping the failures.
pub struct SseFrameReader {
    buffer: String,
}

impl Default for SseFrameReader {
    fn default() -> Self {
        Self::new()
    }
}

impl SseFrameReader {
    pub fn new() -> Self {
        SseFrameReader {
            buffer: String::new(),
        }
    }

    /// What is left after the last chunk — the source passes this to `encoderStream.finish(buffer)`.
    pub fn leftover(&self) -> &str {
        &self.buffer
    }

    /// Feed a chunk; get the payloads it completed, in order. A frame split across two chunks comes out of
    /// the second call.
    ///
    /// **THE CRLF NORMALIZATION IS HERE, AND IT IS WHY A CRLF STREAM WORKS AT ALL.** The `pull` loop does
    /// `buffer = buffer.replace(/\r\n/g, "\n")` BEFORE `parseBuffered`, so the separator really is always
    /// `\n\n` — and my first version of this reader omitted the replace, which would have made a CRLF stream
    /// produce NOTHING. The captured case is named for the truth: it DOES split.
    pub fn push_text(&mut self, text: &str) -> Vec<String> {
        self.buffer.push_str(&text.replace("\r\n", "\n"));
        let mut out = Vec::new();
        while let Some(idx) = self.buffer.find("\n\n") {
            let raw = self.buffer[..idx].to_string();
            self.buffer = self.buffer[idx + 2..].to_string();
            // `raw.split("\n").find(l => l.startsWith("data:"))` — the FIRST such line.
            let Some(data_line) = raw.split('\n').find(|l| l.starts_with("data:")) else {
                continue;
            };
            // `dataLine.slice(5).trim()` — and `slice` on a SHORTER string gives "" rather than raising, so a
            // bare `data:` yields an empty payload, which the caller's parse then drops.
            let payload = data_line.get(5..).unwrap_or("").trim().to_string();
            if payload == "[DONE]" {
                continue;
            }
            out.push(payload);
        }
        out
    }
}

/// **WHAT THE STREAMER DOES WHEN THE STREAM ENDS — the `pull` loop's two endings, as a decision.**
///
/// The source has two ways out and each emits its OWN sentence, which is the part worth porting:
///
/// ```text
///     the reader RAISED     -> "upstream stream died mid-response"   when (buffer || started) && !finished
///     the stream was DONE   -> "upstream returned an empty/non-SSE stream"  when !started
///     either way            -> finish(buffer), which closes the blocks and appends message_delta/message_stop
/// ```
///
/// **THE CONDITIONS ARE NOT SYMMETRIC.** A read failure is only worth reporting if something was in flight —
/// a buffer with unparsed bytes, or an encoder that had started — and the encoder must not already be
/// finished. A CLEAN END is the opposite test: it reports only when NOTHING started, because a stream that
/// carried any chunk at all has already emitted `message_start`.
///
/// AND ONE LINE OF THE SOURCE IS DEAD: the `done` branch computes
/// `const hasDataLine = buffer.split("\n").some((l) => l.startsWith("data:"))` and then does `void hasDataLine`
/// — a leftover from the round that merged the two endings into one sentence. It is NOT ported, and this note
/// is where that decision lives.
pub enum StreamEnd {
    /// Emit this `event: error` frame, then `finish(buffer)` and close.
    ///
    /// This is the READ-FAILURE path: the source enqueues the error, then calls `finish`, then closes.
    EmitError(&'static str),
    /// Emit this `event: error` frame and CLOSE — with NO `finish`.
    ///
    /// **AND THIS IS THE DIFFERENCE I GOT WRONG.** The clean-end path's `!started` branch is
    /// `controller.enqueue(error); controller.close(); return;` — it RETURNS, so no `finish(buffer)` runs and
    /// no `message_start`/`message_delta`/`message_stop` follow. The two error paths are NOT the same shape,
    /// and the captured bytes say so: the empty case's whole output is ONE frame.
    EmitErrorAndStop(&'static str),
    /// Finish and close.
    Finish,
}

pub const STREAM_DIED: &str = "upstream stream died mid-response";
pub const STREAM_EMPTY: &str = "upstream returned an empty/non-SSE stream";

pub fn stream_end_action(
    read_failed: bool,
    leftover: &str,
    started: bool,
    finished: bool,
) -> StreamEnd {
    if read_failed {
        if (!leftover.is_empty() || started) && !finished {
            return StreamEnd::EmitError(STREAM_DIED);
        }
        return StreamEnd::Finish;
    }
    if !started {
        // NOT `EmitError`: this path returns before `finish(buffer)`.
        return StreamEnd::EmitErrorAndStop(STREAM_EMPTY);
    }
    StreamEnd::Finish
}

/// The `event: error` frame the two endings emit — `sse("error", …)` with the type `api_error`.
pub fn stream_error_frame(message: &str) -> String {
    format!(
        "event: error\ndata: {}\n\n",
        serde_json::json!({ "type": "error", "error": { "type": "api_error", "message": message } })
    )
}

/// **THE STREAM TRANSFORM — the `pull` loop's body as a STATE MACHINE, which is what makes it testable.**
///
/// The source's loop, per chunk:
///
/// ```js
/// buffer += decoder.decode(value, { stream: true });
/// buffer = buffer.replace(/\r\n/g, "\n");
/// parseBuffered();
/// const events = encoderStream.take();
/// if (events.length) controller.enqueue(encoder.encode(events));
/// ```
///
/// and at the end, `stream_end_action` + `finish(buffer)`. Every one of those is a decision that was ported
/// and proved; what was missing is the ORDER they run in, which is this struct. The glue around it is a
/// `futures::stream::unfold` over the upstream's `ByteStream` and a `Response::from_stream` — no new
/// dependency, and nothing here that needs a runtime to check.
pub struct StreamTransform {
    reader: SseFrameReader,
    encoder: AnthropicStreamEncoder,
    ended: bool,
}

impl StreamTransform {
    pub fn new(client_model: &str, upstream_model: &str) -> Self {
        StreamTransform {
            reader: SseFrameReader::new(),
            encoder: AnthropicStreamEncoder::new(client_model, upstream_model),
            ended: false,
        }
    }

    /// One upstream chunk in, the bytes to send out (possibly empty).
    pub fn on_chunk(&mut self, text: &str) -> Vec<u8> {
        if self.ended {
            return Vec::new();
        }
        let mut out = String::new();
        for payload in self.reader.push_text(text) {
            // The parse is the CALLER's, which is where the source puts it: a malformed payload is dropped.
            if let Ok(value) = serde_json::from_str::<serde_json::Value>(&payload) {
                let _ = self.encoder.push(&value);
            }
            out.push_str(&self.encoder.take());
        }
        out.into_bytes()
    }

    /// The stream is over: `read_failed` says whether it ended by RAISING or by closing.
    pub fn on_end(&mut self, read_failed: bool) -> Vec<u8> {
        if self.ended {
            return Vec::new();
        }
        self.ended = true;
        let mut out = String::new();
        match stream_end_action(
            read_failed,
            self.reader.leftover(),
            self.encoder.started(),
            self.encoder.finished(),
        ) {
            StreamEnd::EmitError(message) => {
                out.push_str(&stream_error_frame(message));
            }
            StreamEnd::EmitErrorAndStop(message) => {
                // **THE SOURCE RETURNS HERE**, so no `finish` runs and the error frame is the whole output.
                out.push_str(&stream_error_frame(message));
                return out.into_bytes();
            }
            StreamEnd::Finish => {}
        }
        if let Some(tail) = self.encoder.finish(self.reader.leftover()) {
            out.push_str(&tail);
        }
        out.into_bytes()
    }

    pub fn ended(&self) -> bool {
        self.ended
    }
}

#[cfg(test)]
mod frame_tests {
    //! **THE STREAMING PATH'S FRAMING, REPLAYED FROM THE SHIPPING `streamOgToAnthropic`.** Eight captured
    //! cases, each one a rule of the source's `parseBuffered`, and the outputs are SEVEN DISTINCT strings —
    //! the pair that ties is two different input paths converging, which is the correct behaviour and worth
    //! seeing rather than assuming.
    // **EXPLICIT, NOT A GLOB.** `mod tests` below is NESTED INSIDE THIS MODULE — clippy proved it by calling
    // that module's own imports unused while removing them broke the build, which is only possible if it sees
    // these. Naming what this module uses ends the ambiguity a glob leaves.
    use super::{
        stream_end_action, stream_error_frame, AnthropicStreamEncoder, SseFrameReader, StreamEnd,
        StreamTransform,
    };

    fn corpus() -> serde_json::Value {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/fixtures/stream-frame-corpus.json"
        );
        let text = std::fs::read_to_string(path).expect("the frame corpus is committed");
        serde_json::from_str(&text).expect("the corpus parses")
    }

    #[test]
    fn the_framing_and_the_encoder_reproduce_the_captured_stream() {
        let doc = corpus();
        let mut checked = 0;
        let mut outputs: Vec<String> = Vec::new();
        for case in doc["cases"].as_array().expect("cases") {
            let name = case["name"].as_str().unwrap_or("?");
            // The  cases belong to the endings test — this one drives the framing and the encoder only.
            if name.starts_with("end:") {
                continue;
            }
            let mut reader = SseFrameReader::new();
            let mut encoder = AnthropicStreamEncoder::new(
                case["clientModel"].as_str().unwrap_or(""),
                case["upstreamModel"].as_str().unwrap_or(""),
            );
            let mut out = String::new();
            for chunk in case["chunks"].as_array().expect("chunks") {
                let text = chunk.as_str().unwrap_or("");
                for payload in reader.push_text(text) {
                    // **THE PARSE IS THE CALLER'S, WHICH IS WHERE THE SOURCE PUTS IT** — a malformed payload
                    // is swallowed here and the frame is simply lost.
                    if let Ok(value) = serde_json::from_str::<serde_json::Value>(&payload) {
                        let _ = encoder.push(&value);
                    }
                    out.push_str(&encoder.take());
                }
            }
            // **AND THE STREAM ENDS, WHICH IS ITS OWN STEP.** The `pull` loop calls
            // `encoderStream.finish(buffer)` when the reader is done — that is where `content_block_stop`,
            // `message_delta` and `message_stop` come from, and my first version of this replay omitted it and
            // stopped after `content_block_delta`.
            if let Some(tail) = encoder.finish(reader.leftover()) {
                out.push_str(&tail);
            }
            assert_eq!(out, case["expected"].as_str().unwrap_or(""), "{name}");
            outputs.push(out);
            checked += 1;
        }
        assert_eq!(checked, 8, "the frame corpus changed size");
        // **A FLOOR AGAINST A VACUOUS CORPUS.** If a port dropped every frame the outputs would all be the
        // same short string; if it dropped none of the distinctions they would all be distinct. Seven of
        // eight is what the shipping route produces, and the tie is named.
        let distinct: std::collections::HashSet<&String> = outputs.iter().collect();
        assert_eq!(distinct.len(), 7, "the captured outputs changed shape");
    }

    /// **THE TWO ENDINGS, REPLAYED.** Five captured cases and all three behaviours: a read failure AFTER data
    /// was read emits `died mid-response`, the same failure BEFORE anything was read emits NOTHING (the
    /// condition is `(buffer || started)`), and a clean close with nothing started emits `empty/non-SSE`.
    /// **THE STATE MACHINE, DRIVEN BY THE SAME THIRTEEN CASES.** The framing test feeds the chunks through the
    /// pieces directly; this one feeds them through `StreamTransform` — the ORDER the `pull` loop runs them in
    /// — and the two must agree with each other and with the capture.
    ///
    /// A state machine is the thing a loop's order is worth testing with: the framing test could pass with the
    /// steps in the wrong order, and this could not.
    #[test]
    fn the_transform_matches_the_captured_streams() {
        let doc = corpus();
        let mut checked = 0;
        for case in doc["cases"].as_array().expect("cases") {
            let name = case["name"].as_str().unwrap_or("?");
            let mut transform = StreamTransform::new(
                case["clientModel"].as_str().unwrap_or(""),
                case["upstreamModel"].as_str().unwrap_or(""),
            );
            let mut out: Vec<u8> = Vec::new();
            for chunk in case["chunks"].as_array().expect("chunks") {
                out.extend(transform.on_chunk(chunk.as_str().unwrap_or("")));
            }
            out.extend(transform.on_end(case["error"].as_bool().unwrap_or(false)));
            // Anything after the end is ignored, which the source's `controller.close()` does by closing.
            assert!(
                transform.on_end(false).is_empty(),
                "{name}: a second end must emit nothing"
            );
            let got = String::from_utf8(out).expect("the transform emits UTF-8");
            assert_eq!(got, case["expected"].as_str().unwrap_or(""), "{name}");
            checked += 1;
        }
        assert_eq!(checked, 13, "the frame corpus changed size");
    }

    #[test]
    fn the_stream_endings_match_the_shipping_streamer() {
        let doc = corpus();
        let mut died = 0;
        let mut empty = 0;
        let mut silent = 0;
        let mut checked = 0;
        for case in doc["cases"].as_array().expect("cases") {
            let name = case["name"].as_str().unwrap_or("?");
            if !name.starts_with("end:") {
                continue;
            }
            let read_failed = case["error"].as_bool().unwrap_or(false);
            let mut reader = SseFrameReader::new();
            let mut encoder = AnthropicStreamEncoder::new(
                case["clientModel"].as_str().unwrap_or(""),
                case["upstreamModel"].as_str().unwrap_or(""),
            );
            let mut out = String::new();
            for chunk in case["chunks"].as_array().expect("chunks") {
                for payload in reader.push_text(chunk.as_str().unwrap_or("")) {
                    if let Ok(value) = serde_json::from_str::<serde_json::Value>(&payload) {
                        let _ = encoder.push(&value);
                    }
                    out.push_str(&encoder.take());
                }
            }
            match stream_end_action(
                read_failed,
                reader.leftover(),
                encoder.started(),
                encoder.finished(),
            ) {
                StreamEnd::EmitError(message) => {
                    out.push_str(&stream_error_frame(message));
                    died += 1;
                }
                StreamEnd::EmitErrorAndStop(message) => {
                    out.push_str(&stream_error_frame(message));
                    empty += 1;
                    // **NO `finish` ON THIS PATH** — the source returns here.
                    assert_eq!(out, case["expected"].as_str().unwrap_or(""), "{name}");
                    checked += 1;
                    continue;
                }
                StreamEnd::Finish => {
                    if read_failed {
                        silent += 1;
                    }
                }
            }
            if let Some(tail) = encoder.finish(reader.leftover()) {
                out.push_str(&tail);
            }
            assert_eq!(out, case["expected"].as_str().unwrap_or(""), "{name}");
            checked += 1;
        }
        assert_eq!(checked, 5, "the ending cases changed size");
        // **ALL THREE BEHAVIOURS ARE PRESENT, WHICH IS WHAT MAKES THE FIVE CASES WORTH HAVING.**
        assert_eq!(died, 2, "two read failures were after data");
        assert_eq!(empty, 2, "two closes had nothing started");
        assert_eq!(silent, 1, "one read failure came before anything was read");
    }

    #[test]
    fn the_reader_keeps_a_partial_frame_for_the_next_chunk() {
        // The rule a stateless function cannot express, stated directly.
        let mut reader = SseFrameReader::new();
        assert!(
            reader.push_text("data: {\"a\":").is_empty(),
            "a partial frame yields nothing"
        );
        assert_eq!(
            reader.push_text("1}\n\n"),
            vec!["{\"a\":1}".to_string()],
            "and the second chunk completes it"
        );
        // `[DONE]` is skipped rather than passed on.
        assert!(reader.push_text("data: [DONE]\n\n").is_empty());
        // A frame with no `data:` line is skipped.
        assert!(reader.push_text("event: ping\n\n").is_empty());
        // The FIRST `data:` line wins when a frame has two.
        assert_eq!(
            reader.push_text("data: first\ndata: second\n\n"),
            vec!["first".to_string()]
        );
        // **CRLF DOES SPLIT, BECAUSE THE BUFFER IS NORMALIZED FIRST.** The `pull` loop replaces `\r\n` with
        // `\n` BEFORE parsing, so the separator is always `\n\n` in practice. I wrote this pin the other way
        // round — "the separator is `\n\n`, so CRLF does not split" — and the captured case, whose name the
        // oracle now carries, says otherwise.
        assert_eq!(
            reader.push_text("data: x\r\n\r\n"),
            vec!["x".to_string()],
            "CRLF is normalized to LF and then splits"
        );
    }
}

mod tests {
    // **A NAMED, NARROW SUPPRESSION, WITH THE CONTRADICTION THAT EARNED IT.** `rustc` needs these two lines
    // (without them: `cannot find type Value` / `cannot find type AnthropicStreamEncoder`) and `clippy`
    // reports them UNUSED — measured both ways, repeatedly, in this file. Six patch-and-run rounds went into
    // that loop, and the honest end is a suppression that says so rather than an import form that happens to
    // satisfy one of the two tools.
    #[allow(unused_imports)]
    use super::AnthropicStreamEncoder;
    #[allow(unused_imports)]
    use serde_json::Value;

    /// THE FIXTURE IS THE EQUIVALENCE PROOF, and it runs in CI: every case in
    /// `fixtures/stream-corpus.json` was produced by the SHIPPING TypeScript class
    /// (`gateway/wasm/oracle.mjs` drove it), and this replays them here.
    ///
    /// MUTATION: change one character of one case's `expected.events` in the fixture.
    /// RESULT:   fails, naming the case and showing the byte at which the two streams part.
    #[test]
    fn the_typescript_corpus() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/stream-corpus.json");
        let raw = std::fs::read_to_string(path).expect("the fixture is committed");
        let doc: Value = serde_json::from_str(&raw).expect("the fixture is JSON");
        let cases = doc["cases"].as_array().expect("a cases array");
        let mut checked = 0usize;
        let mut threw_cases = 0usize;
        for case in cases {
            let name = case["name"].as_str().unwrap_or("?");
            let mut enc = AnthropicStreamEncoder::new(
                case["clientModel"].as_str().unwrap_or(""),
                case["upstreamModel"].as_str().unwrap_or(""),
            );
            let mut events = String::new();
            let mut raised = false;
            for ch in case["chunks"].as_array().expect("a chunks array") {
                match enc.push(ch) {
                    Ok(()) => events.push_str(&enc.take()),
                    Err(_) => {
                        raised = true;
                        break;
                    }
                }
            }
            let expected = &case["expected"];
            if expected.get("threw").is_some() {
                assert!(
                    raised,
                    "{name}: the TypeScript RAISED on this input and this did not — a port that \
                     accepts what the JavaScript refuses answers a different stream"
                );
                threw_cases += 1;
                checked += 1;
                continue;
            }
            assert!(!raised, "{name}: this raised and the TypeScript did not");
            if let Some(fin) = enc.finish(case["tail"].as_str().unwrap_or("")) {
                events.push_str(&fin);
            }
            // A SECOND finish() must be a no-op, which is part of the contract the corpus recorded.
            if let Some(again) = enc.finish(case["tail"].as_str().unwrap_or("")) {
                events.push_str(&again);
            }
            let want = expected["events"].as_str().unwrap_or("");
            if events != want {
                let at = events
                    .char_indices()
                    .zip(want.char_indices())
                    .find(|((_, a), (_, b))| a != b)
                    .map(|((i, _), _)| i)
                    .unwrap_or(events.len().min(want.len()));
                panic!(
                    "{name}: the two streams part at byte {at}\n  rust: {:?}\n  ts:   {:?}",
                    &events[at.min(events.len())..],
                    &want[at.min(want.len())..]
                );
            }
            assert_eq!(
                enc.started(),
                expected["started"].as_bool().unwrap_or(false),
                "{name}: started"
            );
            assert_eq!(
                enc.finished(),
                expected["finished"].as_bool().unwrap_or(false),
                "{name}: finished"
            );
            checked += 1;
        }
        assert!(
            checked >= 38,
            "the fixture moved: only {checked} case(s) were read, and {threw_cases} of them raise"
        );
    }
}
