// The ORACLE for the landing's colour core: the SHIPPING `agent/scripts/lib/contrast-probe.mjs` is driven
// over a corpus, and what it answered is written out as the fixture the Rust test replays.
//
//   cd index/landing && node oracle.mjs colour > fixtures/colour-corpus.json
//
// The direction matters: the expectations come from the code the panel's sweeps and this page's checks
// both run, not from the port.
import { parseColour, contrastRatio } from "../../agent/scripts/lib/contrast-probe.mjs";

const MODE = process.argv[2] || "colour";

const COLOURS = [
  "#fff", "#FFF", "#f4f4f5", "#71717a", "#bf3a0a", "#000", "#ffff", "#ffffffff", "#f4f4f5cc",
  "#12345", "#1234567", "#", "#gggggg", "#f4f4f", "#f4f4f5f", "#abcdef12",
  "rgb(255,255,255)", "rgb(0, 0, 0)", "rgba(0,0,0,0.5)", "rgb(191, 58, 10)", "RGB(1,2,3)",
  "color(srgb 0.956863 0.956863 0.960784 / 0.88)", "color(srgb 1 0 0)", "color(srgb 1 1 1)",
  "color(srgb 0.5 0.5 0.5)", "color(srgb 2 2 2)", "color(display-p3 1 0 0)",
  "transparent", "none", "", "   ", "foo 1 2 3", "1 2 3", "1 2", "1.5 2.5 3.5 0.25",
  "rgb(1,2,3,4,5)", "..", "-5 -6 -7", "rgb(-1,-2,-3)", "0.5", "rgb(1e2,2e2,3e2)",
  "  #f4f4f5  ", "url(#sky)", "rgb(255 255 255 / 50%)", "hsl(0,0%,100%)",
];

const pairs = [];
for (const fg of COLOURS) {
  for (const bg of ["#ffffff", "#fafafa", "#000000", "rgb(29,29,31)", "color(srgb 0.98 0.98 0.98 / 0.84)"]) {
    const f = parseColour(fg);
    const b = parseColour(bg);
    pairs.push({
      fg,
      bg,
      fgParsed: f,
      bgParsed: b,
      ratio: f && b ? contrastRatio(f, b) : null,
    });
  }
}

if (MODE === "colour") {
  console.log(
    JSON.stringify(
      {
        note: "Generated by index/landing/oracle.mjs colour from the SHIPPING agent/scripts/lib/contrast-probe.mjs. Do not edit by hand.",
        colours: COLOURS.map((c) => ({ input: c, parsed: parseColour(c) })),
        pairs,
      },
      null,
      1,
    ),
  );
  const parsed = COLOURS.filter((c) => parseColour(c)).length;
  const ratios = pairs.filter((p) => p.ratio !== null).length;
  if (parsed < 15 || ratios < 50) {
    console.error(`oracle: the colour corpus moved (${parsed} parsed, ${ratios} ratios)`);
    process.exit(1);
  }
}
