//! EVERY JAVASCRIPT AND TYPESCRIPT FILE IN THIS REPOSITORY, AND WHAT IT IS.
//!
//! **THE CRITERION** (the operator's standing objective, 2026-10-08: *"尽可能只要 Rust"*): every *decision* in the
//! product is Rust, and every remaining JS/TS file is a **named platform boundary** that this gate can name and
//! justify. `worker_language.rs` states the same criterion for one axis — production worker entry points — and this
//! gate states it for every tracked file, including the tests, the harnesses and the views that a worker ratchet
//! cannot see.
//!
//! **FOUR CLASSES, AND THE FIRST ONE IS THE WORK THAT IS LEFT:**
//!
//! | class | means | verdict |
//! |---|---|---|
//! | `LOGIC` | it computes, parses, derives, validates, decides or formats | **must become Rust.** Counted, listed, and ratcheted |
//! | `BOUNDARY` | it performs a platform call and decides nothing — a fetch, a DOM read, a permission, a file written for `browser_run_script` | stays, with the platform call named |
//! | `RENDERING` | it only places what it was given | stays |
//! | `GENERATED` | no human edits it; a build step produces it, and the producer is named AND checked | stays |
//!
//! **A RATCHET, NOT A CHECKLIST — AND THE FIRST DRAFT OF THIS FILE WAS WRONG ABOUT THAT.** It said "fails on any
//! `LOGIC` entry", which is a gate that cannot be green until the migration is finished: it would have been red on
//! every commit from today until the last landing, and a gate that cannot be green is a gate that gets disabled or
//! ignored — the failure this repository has recorded often enough that the rule is written down twice. So `LOGIC`
//! entries are ALLOWED, COUNTED and CAPPED at `MAX_LOGIC`; a landing that migrates a file lowers it in the same
//! commit, and the migration is complete on the day it reaches 0. What the gate refuses is **SILENT growth** and
//! **silence**: a file nobody classified, a `LOGIC` file past the cap, a `GENERATED` entry whose producer does not
//! exist, and a stale cap that no longer matches the list. A raise is possible and has happened once — see the
//! constant — but only in a commit that NAMES the file and the reason, which is the same rule `production_host.rs`
//! follows for its own list, and it is a deliberate edit a reviewer sees in the diff rather than a drift.
//!
//! **THE MANIFEST IS PER DIRECTORY, WITH NAMED FILE EXCEPTIONS**, because a per-file list of 536 entries would be
//! rewritten by every UI change and abandoned within a month. The most specific matching pattern wins, so a rule
//! for `src/wasm/panel_logic.js` beats the rule for `src/`.
//!
//! MUTATION: `touch agent/src/new-helper.mjs` — a file in a directory no rule covers.
//! RESULT:   exit 101 —
//!             these tracked JavaScript/TypeScript files match no rule in the manifest:
//!               agent/src/new-helper.mjs
//!             FIX: add a rule (class | pattern | reason | producer) to agent/tests/fixtures/js-boundaries.txt.
//!
//! MUTATION: `touch gateway/src/new-decisions.ts` — a LOGIC directory grows by one.
//! RESULT:   exit 101 —
//!             LOGIC files: 151, and the frozen budget is 130 — the migration may only shrink this number.
//!             FIX: migrate the file to Rust, or classify it BOUNDARY/RENDERING/GENERATED with a reason.
//!
//! **AND THE THIRD MUTATION IS THE ONE THAT KEEPS THE MANIFEST HONEST** (it is a test below rather than a header
//! line, because it needs no edit to the repository): every `GENERATED` rule must name a producer that exists, so a
//! build step that is renamed or deleted cannot leave a rule claiming a file is generated by nothing.

mod common;

use std::collections::BTreeMap;
use std::path::Path;

/// The classification manifest. One rule per line: `CLASS | pattern | reason | producer`.
const MANIFEST: &str = "agent/tests/fixtures/js-boundaries.txt";

/// A floor, not a claim: the scan must see the repository that exists today. A gate that looked at almost nothing
/// must not pass, and `git ls-files` answering an empty list is exactly how that happens.
const MIN_FILES: usize = 500;

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
enum Class {
    Logic,
    Boundary,
    Rendering,
    Generated,
}

impl Class {
    fn parse(s: &str) -> Option<Self> {
        match s {
            "LOGIC" => Some(Self::Logic),
            "BOUNDARY" => Some(Self::Boundary),
            "RENDERING" => Some(Self::Rendering),
            "GENERATED" => Some(Self::Generated),
            _ => None,
        }
    }

    /// The class's own name, so a report and a failure message spell it the way the manifest does.
    fn name(self) -> &'static str {
        match self {
            Self::Logic => "LOGIC",
            Self::Boundary => "BOUNDARY",
            Self::Rendering => "RENDERING",
            Self::Generated => "GENERATED",
        }
    }
}

#[derive(Debug)]
struct Rule {
    class: Class,
    pattern: String,
    reason: String,
    /// For `GENERATED`: the path of the thing that produces the file. Checked to exist.
    producer: String,
    line: usize,
}

impl Rule {
    fn matches(&self, file: &str) -> bool {
        if self.pattern.ends_with('/') {
            file.starts_with(&self.pattern)
        } else {
            file == self.pattern
        }
    }
}

fn is_js_family(path: &str) -> bool {
    [".js", ".mjs", ".cjs", ".ts", ".tsx"]
        .iter()
        .any(|ext| path.ends_with(ext))
}

fn manifest() -> Vec<Rule> {
    let text = common::read(MANIFEST);
    let mut rules = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = line.split('|').map(str::trim).collect();
        assert!(
            parts.len() >= 3,
            "{MANIFEST}:{}: a rule needs `CLASS | pattern | reason` (and a producer for GENERATED), got: {line}",
            i + 1
        );
        let class = Class::parse(parts[0]).unwrap_or_else(|| {
            panic!(
                "{MANIFEST}:{}: `{}` is not one of LOGIC, BOUNDARY, RENDERING, GENERATED",
                i + 1,
                parts[0]
            )
        });
        let producer = parts.get(3).copied().unwrap_or("").to_string();
        assert!(
            class != Class::Generated || !producer.is_empty(),
            "{MANIFEST}:{}: a GENERATED rule must name its producer in the fourth field — otherwise the rule claims \
             a file is produced by nothing: {line}",
            i + 1
        );
        rules.push(Rule {
            class,
            pattern: parts[1].to_string(),
            reason: parts[2].to_string(),
            producer,
            line: i + 1,
        });
    }
    assert!(!rules.is_empty(), "{MANIFEST} holds no rules at all");
    rules
}

/// The most specific matching rule wins — the longest pattern — so a rule for one file beats the rule for the
/// directory that contains it, and the manifest's ORDER never silently changes a classification.
fn classify<'a>(rules: &'a [Rule], file: &str) -> Option<&'a Rule> {
    rules
        .iter()
        .filter(|r| r.matches(file))
        .max_by_key(|r| r.pattern.len())
}

#[test]
fn every_tracked_js_file_is_classified_and_the_logic_list_only_shrinks() {
    let rules = manifest();
    let files: Vec<String> = common::git_ls_files_all()
        .into_iter()
        .filter(|f| is_js_family(f))
        .collect();

    assert!(
        files.len() >= MIN_FILES,
        "this scan saw only {} JavaScript/TypeScript files (floor {MIN_FILES}) — a gate that looked at almost \
         nothing must not pass",
        files.len()
    );

    let mut counts: BTreeMap<Class, usize> = BTreeMap::new();
    let mut unclassified: Vec<&String> = Vec::new();
    let mut logic: Vec<(&String, &Rule)> = Vec::new();
    for file in &files {
        match classify(&rules, file) {
            None => unclassified.push(file),
            Some(rule) => {
                *counts.entry(rule.class).or_default() += 1;
                if rule.class == Class::Logic {
                    logic.push((file, rule));
                }
            }
        }
    }

    assert!(
        unclassified.is_empty(),
        "these tracked JavaScript/TypeScript files match no rule in the manifest:\n  {}\n\
         FIX: add a rule (class | pattern | reason | producer) to {MANIFEST}.",
        unclassified
            .iter()
            .map(|f| f.as_str())
            .collect::<Vec<_>>()
            .join("\n  ")
    );

    // **AND IT PRINTS THE COUNT ON THE PASSING PATH TOO — ADDED 2026-10-09, BECAUSE READING THE MEASURED CAP
    // USED TO REQUIRE BREAKING THE GATE.** The number lived only in the failure message, so measuring it meant
    // setting the budget to 0, running, reading `LOGIC files: 103`, and restoring — and a measurement nobody
    // can take without a deliberate break is one nobody takes, which is how a cap ends up COMPUTED instead
    // (107 minus the files you moved) rather than measured. Three merges in the session that added this line
    // would have taken arithmetic and been wrong, hence the coordinator's rule.
    //
    // NOTE THE HONEST LIMIT: a test's stdout is captured unless it fails, so this line is visible under
    // `cargo test --test js_boundary_inventory -- --nocapture`. That is one flag rather than one mutation.
    println!(
        "LOGIC files: {} of a frozen budget of {MAX_LOGIC}",
        logic.len()
    );

    // **THE RATCHET, AND IT IS THE POINT OF THE FILE.** The list may shrink; it may not grow, and it may not be
    // silently re-labelled — lowering the cap is a deliberate edit that a reviewer sees in the diff.
    assert!(
        logic.len() <= MAX_LOGIC,
        "LOGIC files: {}, and the frozen budget is {MAX_LOGIC} — the migration may only shrink this number.\n  {}\n\
         FIX: migrate the file to Rust, or classify it BOUNDARY/RENDERING/GENERATED with a reason.",
        logic.len(),
        logic
            .iter()
            .map(|(f, _)| f.as_str())
            .collect::<Vec<_>>()
            .join("\n  ")
    );
    assert!(
        logic.len() >= MAX_LOGIC,
        "LOGIC files: {}, and the frozen budget is {MAX_LOGIC} — the list SHRANK and the cap did not follow it \
         down. A cap left high is finished work wearing a budget.\n\
         FIX: lower MAX_LOGIC to {} in this commit.",
        logic.len(),
        logic.len()
    );

    let total: usize = counts.values().sum();
    let per_class = [
        Class::Logic,
        Class::Boundary,
        Class::Rendering,
        Class::Generated,
    ]
    .iter()
    .map(|c| format!("{} {}", c.name(), counts.get(c).copied().unwrap_or(0)))
    .collect::<Vec<_>>()
    .join(" · ");
    println!("js-boundary: {total} tracked JS/TS files — {per_class}");

    // **THE REMAINING WORK, BY RULE RATHER THAN BY COUNT.** A number is not a plan: the operator reads which
    // directories are still LOGIC and WHY each one is — the reason is the manifest's own fourth column, and
    // printing it here is what keeps it from being decoration.
    if !logic.is_empty() {
        let mut by_rule: BTreeMap<&str, usize> = BTreeMap::new();
        for (_, rule) in &logic {
            *by_rule.entry(rule.pattern.as_str()).or_default() += 1;
        }
        println!(
            "js-boundary: LOGIC remaining, {} file(s) in {} rule(s):",
            logic.len(),
            by_rule.len()
        );
        for (pattern, n) in &by_rule {
            let reason = rules
                .iter()
                .find(|r| r.pattern == *pattern)
                .map(|r| r.reason.as_str())
                .unwrap_or("");
            println!("  {n:>3}  {pattern}\n       {reason}");
        }
    }
}

/// **A `GENERATED` RULE MUST NAME A PRODUCER THAT EXISTS.** This is the direction that keeps the manifest from
/// becoming a place where a build step is claimed and then deleted: rename `sync-code-viewer.sh` and this fails,
/// rather than the mirror quietly becoming "generated by nothing".
#[test]
fn every_generated_rule_names_a_producer_that_exists() {
    let rules = manifest();
    let missing: Vec<String> = rules
        .iter()
        .filter(|r| r.class == Class::Generated)
        .filter(|r| !common::repo().join(&r.producer).exists())
        .map(|r| {
            format!(
                "{MANIFEST}:{}: `{}` is GENERATED by `{}`, which does not exist",
                r.line, r.pattern, r.producer
            )
        })
        .collect();
    assert!(
        missing.is_empty(),
        "a GENERATED rule names a producer that is not there:\n  {}\n\
         FIX: point the rule at the producer that exists, or reclassify the file.",
        missing.join("\n  ")
    );
    let generated = rules.iter().filter(|r| r.class == Class::Generated).count();
    assert!(
        generated > 0,
        "no GENERATED rules at all — the fourth class exists because generated files are not boundaries"
    );
}

/// The matcher's own proof, in the shape the manifest actually meets it: a file rule beats its directory rule, and
/// the ORDER of the two in the file does not decide it.
#[test]
fn the_most_specific_rule_wins_regardless_of_order() {
    let rules = manifest();
    let file = "agent/resources/panel-react/src/wasm/panel_logic.js";
    let rule = classify(&rules, file).expect("panel_logic.js is classified");
    assert_eq!(
        rule.class,
        Class::Generated,
        "{file} is wasm-bindgen output; the rule that catches it is `{}` (line {}), and a directory rule must not \
         win over it by appearing first",
        rule.pattern,
        rule.line
    );
    // ...and a sibling that is NOT generated is not swept up by that rule.
    let seam = classify(&rules, "agent/resources/panel-react/src/wasm/panelLogic.ts")
        .expect("the seam is classified");
    assert_eq!(
        seam.class,
        Class::Boundary,
        "the hand-written seam beside the generated glue must not inherit its class"
    );
    assert!(
        Path::new(&rule.producer).exists() || common::repo().join(&rule.producer).exists(),
        "the generated glue's producer must exist: {}",
        rule.producer
    );
}

/// **THE RATCHET, AND THE HISTORY OF THE NUMBER.** The count of `LOGIC` files today; it may only fall, and when it
/// reaches 0 the criterion is met — which is the day `assert_eq!(logic.len(), MAX_LOGIC)` stops being a cap and
/// starts being the sentence the migration was always meant to say. A cap left high is finished work wearing a
/// budget, so every movement below is the number THE GATE measured on the merged tree, in the commit that caused
/// it, and never a number a branch carried in its pocket.
///
/// THE MOVEMENTS ON 2026-10-09, in order, because two of them were measured on branches that had not seen the
/// others — and that is exactly the case where a number has to be re-derived rather than inherited:
///
///     the six-file sweep audit      152 -> 146   six sweep payload files became BOUNDARY
///     landing 5 slice 2 (identity)  146 -> 147   + gateway/test/auth-cutover.test.mjs
///     landing 5 slice 3 (MCP)       147 -> 147   mcp-tools.ts became GENERATED (−1) and
///                                                 mcp-cutover.test.mjs entered (+1): a net zero
///     landing 6 (electron)          ->   145     − url-policy.ts and its suite, which became the
///                                                 summrise-url-policy crate's own tests
///     the boot check is a gate      ->   144     harness-boot-check.mjs became a cargo gate
///     the workspaces check          ->   143     verify-workspaces-page.mjs's judgement, and its
///                                                 hand-kept list DELETED in favour of deriving it
///     the notes are the judge's     ->   142     ackNotes left design-sweep.mjs, which is a driver now
///     the gates' six ports          ->   142     unchanged: the .mjs stays beside its Rust for the
///                                                 differential, so the class does not move yet
///     the relay is cut over         ->   110     the biggest single drop, and the only one whose
///                                                 evidence is a PRODUCTION change: see below
///     the live probe's rule         ->   109     `live-panel-probe.mjs` had NO RULE, so the
///                                                 catch-all made it LOGIC: a manifest gap, not a port
///     the orphaned helper           ->   108     `scripts/test/lib/decomment.mjs` DELETED: its rule
///                                                 has one definition now, and it is in Rust
///     the fixture reader            ->   107     `scripts/test/lib/emitted-pieces.mjs` is what two
///                                                 live bash gates import, so it is BOUNDARY
///     landing 6b (electron)         ->   103     − main.ts and preload.ts, which are the shell's HOST
///                                                 now (its decisions are `summrise-shell-policy`,
///                                                 wasm), and − ipc-door.test.mjs and
///                                                 embedded-bridge.test.mjs, which pin the HOST's
///                                                 call-site counts and the preload's bridge names.
///                                                 FOUR files, named because a cap may only come DOWN
///                                                 in a commit that says which file left
///
/// **THE LANDING 6b ROW IS THE FIRST ONE MEASURED RATHER THAN COMPUTED, AND THAT IS THE RULE.** Four files
/// leaving four directory rules is arithmetic anyone can do, and arithmetic is not a measurement: the
/// number below is what THIS GATE PRINTS on the tree that carries the reclassification, and it was
/// re-derived after the manifest change rather than predicted before it. (Three merges this session
/// resolved a cap conflict by running the gate and taking its number; twice the computed answer would have
/// been wrong.)
///
/// **AND TWO MORE MOVED FOR A THIRD REASON: ONE WAS ALREADY GONE IN EVERY SENSE BUT THE FILE.** The rule
/// `scripts/test/lib/decomment.mjs` defines — a comment is not a producer, nor a derivation — has exactly one
/// definition in Rust (`agent/tests/common/mod.rs`), whose header says it took the rule FROM that file, and
/// nothing imported the `.mjs` any more. Measured the way this repository requires before calling something
/// unused: `git grep -nE '(from|import|require).*decomment' -- '*.mjs' '*.cjs' '*.js'` returned ONE line, a
/// comment in its sibling naming it. So it is DELETED rather than reclassified — a file whose rule moved and
/// whose importers moved with it is not a boundary, it is a leftover wearing one. Its SIBLING stayed for the
/// opposite reason and got a rule: `emitted-pieces.mjs` is imported by two live bash gates
/// (`panel-design-sweep.bash:92`, `sweep-judges.bash:134`), so it is their fixture reader — the same reading
/// the sweeps' in-page probes get.
///
/// **AND ONE FILE MOVED FOR A DIFFERENT REASON ENTIRELY: IT HAD NO RULE.** `agent/scripts/live-panel-probe.mjs`
/// fell through to the catch-all `LOGIC | agent/scripts/` because nobody had written its rule — while `AGENTS.md`
/// already carried the carve-out in its own table ("the device calls it through `browser_run_script`, which takes
/// a JS file, and the measurement runs in the DOM") and its exact sibling, `panel-render-audit.mjs`, was already
/// BOUNDARY two rules above. A catch-all does not classify what it swallows; it hides it. The rule now names what
/// the file is — an EMITTER whose product is a program a browser runs — and says the thing that matters most about
/// it: **its verdict is not enforced by any job**, because it runs on a device and its numbers are read by a
/// person. What it measures that no harness can is the LIVE panel's geometry (round 167: 1488 root nodes and 14
/// live sessions against the harness's 366 and three), which is why it is kept rather than deleted.
///
/// **THE RELAY'S TWENTY FILES DID NOT MOVE BECAUSE THE PORT FINISHED.** THEY MOVED BECAUSE THE CUTOVER
/// HAPPENED** — and the difference matters, because "the Rust exists" was already true a week earlier while
/// the JavaScript was still the thing answering. On 2026-10-09 nginx's `/api/` was pointed at the Rust relay
/// on `127.0.0.1:8082` and the cutover was PROVED by stopping the Node unit: with only the Rust one listening,
/// the public endpoint still answered **401** to an unauthenticated `POST /api/proxy`. From that moment the
/// JavaScript decides nothing the product depends on, and the three roles it DOES still hold are all boundary
/// roles, each named in the manifest: `ci.yml` calls its suite "the ORACLE the committed fixture was generated
/// from"; `proxy_timeout_parity.rs`, `proxy_cors_parity.rs` and `relay/tests/two_relays_agree.rs` read its
/// SOURCE as their text oracle; and `relay/differential.mjs` needs both implementations present to compare
/// their answers byte for byte (14/14, 0 unexplained). The Node bundle also stays deployed as the one-line
/// rollback. Deleting these files would delete the proof and the fallback — the migration's own rule is that
/// an instrument which exists to be compared WITH is a boundary, which is what `index/src/index.js`,
/// `gateway/wasm/verify.mjs` and `agent/summrise-cli/parity/` already are.
///
/// **WHY THE LAST ROW IS NOT A SLICE'S OWN NUMBER.** Each branch above measured its movement against the tree it
/// knew. The identity branch's base read 152 and it raised ITS cap to 153; the audit had already moved six files
/// out, so its real base was 146 and its net was +1. The merger's job is not to pick a side but to run the gate on
/// the merged tree and lower the constant to what it prints — which is what happened, three times, and the drop is
/// bigger than the gap because the sweeps' audits and the six reclassifications landed between the branches.
///
/// **THE RULE, STATED SO THE NEXT RAISE IS JUDGED RATHER THAN FELT:** silent growth is refused, and a raise is
/// allowed only in a commit that NAMES the file and the reason — the same rule `production_host.rs` follows for
/// its own list. And a cap may only come DOWN in a commit that also says which file left, because a number that
/// falls without its reason is a number that cannot be audited.
///
/// AND ONE MOVEMENT IS DELIBERATELY ZERO NAMED, SO THAT "UNCHANGED" IS NOT MISTAKEN FOR "NOTHING HAPPENED":
/// the MCP slice moved `gateway/src/mcp-tools.ts` OUT of this class — its single source is
/// `gateway/wasm/src/mcp_tools.rs`, and the TypeScript copy is now its EMISSION, checked byte for byte by a
/// cargo test, GENERATED with the crate named as producer — and added `gateway/test/mcp-cutover.test.mjs`, which
/// pins which half serves `/mcp` in both configurations and pins the one route the slice does not port
/// (`GET /api/plugins/status`, whose `routes` field is the TypeScript plugin registry's own dispatch counters).
/// A ratchet that moves for a file that merely changed class is measuring the manifest rather than the work.
///
/// **AND ONE MOVEMENT TOOK A RULE WITH IT, WHICH IS THE PART WORTH READING (2026-10-09).**
/// `scripts/model-drift.mjs` (137 lines) is `agent/model-drift/` now: the three pure functions, the
/// report's sentences, the argv and the exit codes are Rust, and `cargo test -p summrise-model-drift`
/// — named in the `agent` job, because a workspace member that is not a default member is a crate no
/// job tests — is what runs the ported cases. Its manifest rule was not only its own: the catch-all
/// `LOGIC | scripts/ | the root build/release tooling (landing 3)` matched that file and NOTHING ELSE
/// (the rest of `scripts/` is extensionless hook scripts, which this inventory does not count, and
/// `scripts/test/` is covered by its own longer rule), so once the file left, the rule matched
/// nothing — and a rule that matches nothing is dead weight in the file that answers "may I write
/// this in JS". It is deleted with the file, which is also what makes a future `.mjs` in `scripts/`
/// land as UNCLASSIFIED instead of being quietly swallowed by a directory rule. The number below was
/// MEASURED, not computed: the cap was set to 0 and the gate's own failure line read back on THIS
/// tree (`LOGIC files: 106, and the frozen budget is 0`), because only the merged tree's number is a
/// fact about the merged tree.
///
/// AND THE SOUND OF A DOWNWARD STEP IS NAMED: the two files landing 6 removed did not go away because they were
/// inconvenient. `agent/summrise-desktop-electron/src/url-policy.ts` and its suite became
/// `agent/summrise-url-policy`'s own tests, case for case, in a Rust crate compiled to wasm — the shell's
/// URL/origin/certificate policy is now machine-checked in the language of the policy. The wasm-pack products that
/// landing ADDED are GENERATED rules with the crate named as producer, and the Node suite that loads the committed
/// artifact in CI's place is a BOUNDARY exception because it executes an artifact and decides nothing.
///
/// **IT FELL BY FIVE ON 2026-10-09, AND THE FIVE ARE NAMED** — the rule this constant carries is that a cap may
/// come down only in a commit that says which file left, so that a number which falls without its reason cannot
/// be audited:
///
///   `scripts/test/console-assets-check.mjs`        -> `agent/tests/console_assets.rs`
///   `scripts/test/console-smoke-check.mjs`         -> `agent/tests/console_smoke.rs`
///   `scripts/test/panel-sheet-freshness-check.mjs` -> `agent/tests/panel_sheet_freshness.rs`
///   `scripts/test/press-anchor-check.mjs`          -> `agent/tests/press_anchor.rs`
///   `scripts/test/contrast-probe-check.mjs`        -> `agent/tests/contrast_probe.rs` (13 assertions) plus
///                                                     `agent/tests/contrast_probe_emitted.rs` (5)
///
/// Each was ported with the Node gate still beside it, the two were run on one tree until they agreed, and the
/// `.mjs` was deleted — the differential is in the commit that landed each port. The `scripts/test/` manifest
/// rule STAYS and is not narrowed: `scripts/test/npm-test-floored.mjs` is still there on purpose, because only
/// its DECISION moved (`agent/tests/npm_test_floor.rs`) and the spawn that runs `npm test` in six directories
/// has not. **107 -> 102.**
///
///     landing 4b's cutover         102 -> 101   `agent/summrise-agent-npm/src/summrise.ts` LEFT (and its `bin/`
///                                                GENERATED rule with it): the npm `bin` is `bin/summrise.exe`, a
///                                                cargo artifact, so the TypeScript CLI and the tsc emit that
///                                                regenerated nothing are deleted. Its 68-case suite left too and
///                                                the packaging suite took the directory's place — ONE step and not
///                                                two, and the number did not move for the suite, because a test
///                                                belongs to the code it tests and this one now tests the tarball.
///
/// **AND THE TWO NUMBERS IN THAT PARAGRAPH ARE MEASURED ON THE MERGED TREE, NOT CARRIED FROM THE BRANCH THAT
/// WROTE THEM.** It arrived saying `107 -> 106`, which was true on ITS base; this tree already carried the five
/// `.mjs` gates' `107 -> 102`, so the same landing reads `102 -> 101` here. The count came from the gate's own
/// refusal — `const MAX_LOGIC` forced to **0**, which makes it print `LOGIC files: 101, and the frozen budget
/// is 0` — because a cap resolved by picking one branch's number is a cap nobody measured.
/// **AND THE SAME PARAGRAPH, ONE LANDING LATER, FOR THE FOUR FILES THAT LEFT IN 6b.** `main.ts` and
/// `preload.ts` did not stop mattering — they are the shell's HOST, and they are the ONLY two files in this
/// repository that can create an Electron window or hold CDP :9333 open. What changed is that they decide
/// nothing any more: the ~58 decision sites a classification found in `main.ts` (made before a line of Rust
/// was written, and reported with line ranges) are `agent/summrise-shell-policy`'s, compiled to wasm and
/// required the same way `agent/summrise-url-policy` is. The two `.mjs` files stayed and moved class for
/// the manifest's own reason — "a test belongs to the code it tests" — and what they test is now the host:
/// call-site counts in `main.ts`'s text and the preload's bridge names against the panel's fixture. A
/// directory whose rule says LOGIC while every file in it is a boundary is the manifest lying to itself.
///
/// **101 -> 97, AND THE NUMBER IS MEASURED ON THE MERGED TREE RATHER THAN CARRIED FROM EITHER BRANCH.** The
/// paragraph above measured 101 on the integration branch BEFORE this landing's conflicts were resolved, so
/// its four files could not be counted yet; this branch's own reading was 103 on ITS base, where the five
/// `.mjs` gates and the CLI's cutover had not landed. Neither number is the merged tree's. The gate's own
/// refusal settles it — `const MAX_LOGIC` forced to **0**, which prints `LOGIC files: 97, and the frozen
/// budget is 0` — and the four names are in the paragraph above. **A cap resolved by picking a branch's
/// number is a cap nobody measured**, which is the rule the paragraph above states and this one obeys.
///
///     the contrast verdict    97 -> 95   `agent/scripts/lib/sweep/panel-run.cjs` and `lib/sweep/console-run.cjs`
///                                         LEFT: the two payloads that carried the under-AA comparison are BOUNDARY
///                                         now (they build a payload and decide nothing), and the JUDGE is Rust —
///                                         `summrise-sweep-judge` plus the same clause in `summrise-command-core`'s
///                                         `sweep_judge.rs`. **`agent/scripts/` NO LONGER APPEARS IN THE LOGIC-
///                                         REMAINING RULES AT ALL**: these were the last two, which is the whole
///                                         point of the design-sweep item. Verified by replaying **119 recorded
///                                         rows** through the Rust judge one at a time — 61 panel + 58 console,
///                                         sentence against sentence, 0 differences.
///
/// **AND 97 -> 95 IS MEASURED HERE, NOT CARRIED.** The branch that wrote this landing says `107 -> 105`, which
/// was true on ITS base; this tree had already taken the five `.mjs` gates, the CLI's cutover and the Electron
/// shell, so the same landing reads `97 -> 95`. The count came from forcing this constant to **0** and reading
/// the gate's own refusal: `LOGIC files: 95, and the frozen budget is 0`. Three different branches produced
/// three different numbers for one landing today; **only the merged tree's is a fact about the merged tree.**
///
///     the model-drift tool     95 -> 94   `scripts/model-drift.mjs` LEFT: its three decisions (the name
///                                         normalisation, the advertised/offered diff, and the report's own
///                                         sentences) are `summrise-model-drift`, a crate with a binary. **THE
///                                         MANIFEST'S `LOGIC | scripts/ |` RULE WENT WITH IT** — that file was
///                                         its only `.js` match (the rest of `scripts/` is extensionless hook
///                                         scripts, which this gate does not count), so the rule was deleted
///                                         rather than left matching nothing.
///
/// **AND THIS NUMBER IS 94 BECAUSE IT WAS MEASURED ON THIS TREE, NOT BECAUSE 95 - 1 = 94.** The branch that
/// wrote the port reported **106** — correctly, on ITS base, which was `main` (107). Both numbers were right
/// about their own trees; only this one is about this one. The gate's own refusal, with the constant forced
/// to 0, is where it came from: `LOGIC files: 94`.
const MAX_LOGIC: usize = 94;
