//! EVERY JAVASCRIPT AND TYPESCRIPT FILE IN THIS REPOSITORY, AND WHAT IT IS.
//!
//! **THE CRITERION** (the operator's standing objective, 2026-10-08: *"尽可能只要 Rust"*): every *decision* in the
//! product is Rust, and every remaining JS/TS file is a **named platform boundary** that this gate can name and
//! justify. `worker_language.rs` states the same criterion for one axis — production worker entry points — and this
//! gate states it for every tracked file, including the tests, the harnesses and the views that a worker ratchet
//! cannot see.
//!
//! **FOUR CLASSES, AND THE FIRST ONE IS THE WORK THAT IS LEFT:**
//!
//! | class | means | verdict |
//! |---|---|---|
//! | `LOGIC` | it computes, parses, derives, validates, decides or formats | **must become Rust.** Counted, listed, and ratcheted |
//! | `BOUNDARY` | it performs a platform call and decides nothing — a fetch, a DOM read, a permission, a file written for `browser_run_script` | stays, with the platform call named |
//! | `RENDERING` | it only places what it was given | stays |
//! | `GENERATED` | no human edits it; a build step produces it, and the producer is named AND checked | stays |
//!
//! **A RATCHET, NOT A CHECKLIST — AND THE FIRST DRAFT OF THIS FILE WAS WRONG ABOUT THAT.** It said "fails on any
//! `LOGIC` entry", which is a gate that cannot be green until the migration is finished: it would have been red on
//! every commit from today until the last landing, and a gate that cannot be green is a gate that gets disabled or
//! ignored — the failure this repository has recorded often enough that the rule is written down twice. So `LOGIC`
//! entries are ALLOWED, COUNTED and CAPPED at `MAX_LOGIC`; a landing that migrates a file lowers it in the same
//! commit, and the migration is complete on the day it reaches 0. What the gate refuses is **SILENT growth** and
//! **silence**: a file nobody classified, a `LOGIC` file past the cap, a `GENERATED` entry whose producer does not
//! exist, and a stale cap that no longer matches the list. A raise is possible and has happened once — see the
//! constant — but only in a commit that NAMES the file and the reason, which is the same rule `production_host.rs`
//! follows for its own list, and it is a deliberate edit a reviewer sees in the diff rather than a drift.
//!
//! **THE MANIFEST IS PER DIRECTORY, WITH NAMED FILE EXCEPTIONS**, because a per-file list of 536 entries would be
//! rewritten by every UI change and abandoned within a month. The most specific matching pattern wins, so a rule
//! for `src/wasm/panel_logic.js` beats the rule for `src/`.
//!
//! MUTATION: `touch agent/src/new-helper.mjs` — a file in a directory no rule covers.
//! RESULT:   exit 101 —
//!             these tracked JavaScript/TypeScript files match no rule in the manifest:
//!               agent/src/new-helper.mjs
//!             FIX: add a rule (class | pattern | reason | producer) to agent/tests/fixtures/js-boundaries.txt.
//!
//! MUTATION: `touch gateway/src/new-decisions.ts` — a LOGIC directory grows by one.
//! RESULT:   exit 101 —
//!             LOGIC files: 151, and the frozen budget is 130 — the migration may only shrink this number.
//!             FIX: migrate the file to Rust, or classify it BOUNDARY/RENDERING/GENERATED with a reason.
//!
//! **AND THE THIRD MUTATION IS THE ONE THAT KEEPS THE MANIFEST HONEST** (it is a test below rather than a header
//! line, because it needs no edit to the repository): every `GENERATED` rule must name a producer that exists, so a
//! build step that is renamed or deleted cannot leave a rule claiming a file is generated by nothing.

mod common;

use std::collections::BTreeMap;
use std::path::Path;

/// The classification manifest. One rule per line: `CLASS | pattern | reason | producer`.
const MANIFEST: &str = "agent/tests/fixtures/js-boundaries.txt";

/// **THE RATCHET.** The number of `LOGIC` files today; it may only fall. When it reaches 0 the criterion is met and
/// the class is empty — which is the day `assert_eq!(logic.len(), MAX_LOGIC)` stops being a cap and starts being
/// the sentence the criterion was always meant to be.
///
/// UNCHANGED BY SLICE 1 OF LANDING 2b, and that is the honest reading: the plan moved out of the payloads into
/// Rust, but the payload FILES are still here (the driving is a later slice), so no file left this class. The two
/// JavaScript halves the landing ADDED — `agent/scripts/lib/sweep-plan.mjs`, which runs the plan binary at emit
/// time, and `agent/scripts/lib/sweep/plan-runtime.cjs`, which places what the plan gave it — are BOUNDARY
/// exceptions to the `agent/scripts/` rule, so they never entered it. A cap lowered for files that never joined
/// the class would be finished work wearing a budget.
///
/// **IT WENT UP BY ONE ON 2026-10-08, AND THE GATE IS WHAT SAID SO — which is the only way this number is allowed
/// to move in that direction.** Porting the console's device registry added `gateway/test/devices-cutover.test.mjs`
/// (131 lines): the test that pins WHICH half serves `/api/devices*` in both configurations, written because the
/// first version of that predicate would have kept the public `POST /api/devices/self-register` on the TypeScript
/// path forever — the bug the test exists to catch. It sits in `gateway/test/`, a LOGIC directory, because that
/// directory's files only leave when the TypeScript they exercise does. So the count went 151 -> 152, the cap
/// followed it in the same commit, and the alternative — folding the file into `devices.test.mjs` to keep the
/// number at 151 — was rejected: a ratchet that is satisfied by moving a file is a ratchet that measures nothing.
/// **THE RULE, stated so the next raise is judged rather than felt: silent growth is refused, and a raise is
/// allowed only in a commit that NAMES the file and the reason** — the same rule `production_host.rs` follows for
/// its own list.
const MAX_LOGIC: usize = 152;

/// A floor, not a claim: the scan must see the repository that exists today. A gate that looked at almost nothing
/// must not pass, and `git ls-files` answering an empty list is exactly how that happens.
const MIN_FILES: usize = 500;

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
enum Class {
    Logic,
    Boundary,
    Rendering,
    Generated,
}

impl Class {
    fn parse(s: &str) -> Option<Self> {
        match s {
            "LOGIC" => Some(Self::Logic),
            "BOUNDARY" => Some(Self::Boundary),
            "RENDERING" => Some(Self::Rendering),
            "GENERATED" => Some(Self::Generated),
            _ => None,
        }
    }

    /// The class's own name, so a report and a failure message spell it the way the manifest does.
    fn name(self) -> &'static str {
        match self {
            Self::Logic => "LOGIC",
            Self::Boundary => "BOUNDARY",
            Self::Rendering => "RENDERING",
            Self::Generated => "GENERATED",
        }
    }
}

#[derive(Debug)]
struct Rule {
    class: Class,
    pattern: String,
    reason: String,
    /// For `GENERATED`: the path of the thing that produces the file. Checked to exist.
    producer: String,
    line: usize,
}

impl Rule {
    fn matches(&self, file: &str) -> bool {
        if self.pattern.ends_with('/') {
            file.starts_with(&self.pattern)
        } else {
            file == self.pattern
        }
    }
}

fn is_js_family(path: &str) -> bool {
    [".js", ".mjs", ".cjs", ".ts", ".tsx"]
        .iter()
        .any(|ext| path.ends_with(ext))
}

fn manifest() -> Vec<Rule> {
    let text = common::read(MANIFEST);
    let mut rules = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = line.split('|').map(str::trim).collect();
        assert!(
            parts.len() >= 3,
            "{MANIFEST}:{}: a rule needs `CLASS | pattern | reason` (and a producer for GENERATED), got: {line}",
            i + 1
        );
        let class = Class::parse(parts[0]).unwrap_or_else(|| {
            panic!(
                "{MANIFEST}:{}: `{}` is not one of LOGIC, BOUNDARY, RENDERING, GENERATED",
                i + 1,
                parts[0]
            )
        });
        let producer = parts.get(3).copied().unwrap_or("").to_string();
        assert!(
            class != Class::Generated || !producer.is_empty(),
            "{MANIFEST}:{}: a GENERATED rule must name its producer in the fourth field — otherwise the rule claims \
             a file is produced by nothing: {line}",
            i + 1
        );
        rules.push(Rule {
            class,
            pattern: parts[1].to_string(),
            reason: parts[2].to_string(),
            producer,
            line: i + 1,
        });
    }
    assert!(!rules.is_empty(), "{MANIFEST} holds no rules at all");
    rules
}

/// The most specific matching rule wins — the longest pattern — so a rule for one file beats the rule for the
/// directory that contains it, and the manifest's ORDER never silently changes a classification.
fn classify<'a>(rules: &'a [Rule], file: &str) -> Option<&'a Rule> {
    rules
        .iter()
        .filter(|r| r.matches(file))
        .max_by_key(|r| r.pattern.len())
}

#[test]
fn every_tracked_js_file_is_classified_and_the_logic_list_only_shrinks() {
    let rules = manifest();
    let files: Vec<String> = common::git_ls_files_all()
        .into_iter()
        .filter(|f| is_js_family(f))
        .collect();

    assert!(
        files.len() >= MIN_FILES,
        "this scan saw only {} JavaScript/TypeScript files (floor {MIN_FILES}) — a gate that looked at almost \
         nothing must not pass",
        files.len()
    );

    let mut counts: BTreeMap<Class, usize> = BTreeMap::new();
    let mut unclassified: Vec<&String> = Vec::new();
    let mut logic: Vec<(&String, &Rule)> = Vec::new();
    for file in &files {
        match classify(&rules, file) {
            None => unclassified.push(file),
            Some(rule) => {
                *counts.entry(rule.class).or_default() += 1;
                if rule.class == Class::Logic {
                    logic.push((file, rule));
                }
            }
        }
    }

    assert!(
        unclassified.is_empty(),
        "these tracked JavaScript/TypeScript files match no rule in the manifest:\n  {}\n\
         FIX: add a rule (class | pattern | reason | producer) to {MANIFEST}.",
        unclassified
            .iter()
            .map(|f| f.as_str())
            .collect::<Vec<_>>()
            .join("\n  ")
    );

    // **THE RATCHET, AND IT IS THE POINT OF THE FILE.** The list may shrink; it may not grow, and it may not be
    // silently re-labelled — lowering the cap is a deliberate edit that a reviewer sees in the diff.
    assert!(
        logic.len() <= MAX_LOGIC,
        "LOGIC files: {}, and the frozen budget is {MAX_LOGIC} — the migration may only shrink this number.\n  {}\n\
         FIX: migrate the file to Rust, or classify it BOUNDARY/RENDERING/GENERATED with a reason.",
        logic.len(),
        logic
            .iter()
            .map(|(f, _)| f.as_str())
            .collect::<Vec<_>>()
            .join("\n  ")
    );
    assert!(
        logic.len() >= MAX_LOGIC,
        "LOGIC files: {}, and the frozen budget is {MAX_LOGIC} — the list SHRANK and the cap did not follow it \
         down. A cap left high is finished work wearing a budget.\n\
         FIX: lower MAX_LOGIC to {} in this commit.",
        logic.len(),
        logic.len()
    );

    let total: usize = counts.values().sum();
    let per_class = [
        Class::Logic,
        Class::Boundary,
        Class::Rendering,
        Class::Generated,
    ]
    .iter()
    .map(|c| format!("{} {}", c.name(), counts.get(c).copied().unwrap_or(0)))
    .collect::<Vec<_>>()
    .join(" · ");
    println!("js-boundary: {total} tracked JS/TS files — {per_class}");

    // **THE REMAINING WORK, BY RULE RATHER THAN BY COUNT.** A number is not a plan: the operator reads which
    // directories are still LOGIC and WHY each one is — the reason is the manifest's own fourth column, and
    // printing it here is what keeps it from being decoration.
    if !logic.is_empty() {
        let mut by_rule: BTreeMap<&str, usize> = BTreeMap::new();
        for (_, rule) in &logic {
            *by_rule.entry(rule.pattern.as_str()).or_default() += 1;
        }
        println!(
            "js-boundary: LOGIC remaining, {} file(s) in {} rule(s):",
            logic.len(),
            by_rule.len()
        );
        for (pattern, n) in &by_rule {
            let reason = rules
                .iter()
                .find(|r| r.pattern == *pattern)
                .map(|r| r.reason.as_str())
                .unwrap_or("");
            println!("  {n:>3}  {pattern}\n       {reason}");
        }
    }
}

/// **A `GENERATED` RULE MUST NAME A PRODUCER THAT EXISTS.** This is the direction that keeps the manifest from
/// becoming a place where a build step is claimed and then deleted: rename `sync-code-viewer.sh` and this fails,
/// rather than the mirror quietly becoming "generated by nothing".
#[test]
fn every_generated_rule_names_a_producer_that_exists() {
    let rules = manifest();
    let missing: Vec<String> = rules
        .iter()
        .filter(|r| r.class == Class::Generated)
        .filter(|r| !common::repo().join(&r.producer).exists())
        .map(|r| {
            format!(
                "{MANIFEST}:{}: `{}` is GENERATED by `{}`, which does not exist",
                r.line, r.pattern, r.producer
            )
        })
        .collect();
    assert!(
        missing.is_empty(),
        "a GENERATED rule names a producer that is not there:\n  {}\n\
         FIX: point the rule at the producer that exists, or reclassify the file.",
        missing.join("\n  ")
    );
    let generated = rules.iter().filter(|r| r.class == Class::Generated).count();
    assert!(
        generated > 0,
        "no GENERATED rules at all — the fourth class exists because generated files are not boundaries"
    );
}

/// The matcher's own proof, in the shape the manifest actually meets it: a file rule beats its directory rule, and
/// the ORDER of the two in the file does not decide it.
#[test]
fn the_most_specific_rule_wins_regardless_of_order() {
    let rules = manifest();
    let file = "agent/resources/panel-react/src/wasm/panel_logic.js";
    let rule = classify(&rules, file).expect("panel_logic.js is classified");
    assert_eq!(
        rule.class,
        Class::Generated,
        "{file} is wasm-bindgen output; the rule that catches it is `{}` (line {}), and a directory rule must not \
         win over it by appearing first",
        rule.pattern,
        rule.line
    );
    // ...and a sibling that is NOT generated is not swept up by that rule.
    let seam = classify(&rules, "agent/resources/panel-react/src/wasm/panelLogic.ts")
        .expect("the seam is classified");
    assert_eq!(
        seam.class,
        Class::Boundary,
        "the hand-written seam beside the generated glue must not inherit its class"
    );
    assert!(
        Path::new(&rule.producer).exists() || common::repo().join(&rule.producer).exists(),
        "the generated glue's producer must exist: {}",
        rule.producer
    );
}
