// landing-run.cjs — the landing sweep's DEVICE-SIDE program, as a real module.
//
// IT USED TO BE A TEMPLATE LITERAL inside landing-design-sweep.mjs: the whole program, with `PROBE`, the six passes
// and the page checks spliced in as text (`${JSON.stringify(PROBE_SOURCE)}`, `${focusPass.toString()}`,
// `${pageChecks("body")}`). That is the shape this round is removing: a comment in a pass, a backtick in a probe's
// doc, or a stray backslash in a regex all had to survive being ESCAPED INTO a host file, and 53 incidents say they
// did not. Here the program is ordinary code. The pieces that genuinely vary per run (paths, the baked stamp, the
// passes, the probe texts) arrive as a real module — `./pieces.cjs`, generated by the emitter — so nothing is
// escaped and nothing is hand-listed as "must also be embedded".
//
// THE BEHAVIOUR IS UNCHANGED, and that is deliberate: the first migrated emitter has to produce the same report as
// the one it replaces, field for field (round 266's equivalence bar), so this file is the old payload with its
// interpolations turned into requires.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const P = require("./pieces.cjs");

const ROOT = process.env.VALE_SWEEP_ROOT || P.config.root;
const REPORT_PATH = process.env.VALE_SWEEP_REPORT || P.config.reportPath;
const EXPECTED_ENTRY = P.config.expectedEntry;
const EXPECTED_ENTRY_PATH = path.join(ROOT, "installer.html");
const PROBE = P.probe;
const UNSTYLED = P.unstyled;
const TARGETS = P.targets;
const SURFACE = P.checks.SURFACE;
const NAMES = P.checks.NAMES;
const REFLOW = P.checks.REFLOW;
// THE ROOT SELECTOR IS AN ARGUMENT TO THE PROBES (round 271): it used to be substituted into their source text,
// which is how a Node-side identifier once reached page code. The mark axis travels with the surface probe's
// result, so it is evaluated alongside it and merged in, exactly where it used to be spliced.
const MARKS = P.marks;
const SELECTOR = P.config.selector;
const focusPass = P.passes.focusPass;
const pressDelta = P.passes.pressDelta;
const pressPass = P.passes.pressPass;
const idlePass = P.passes.idlePass;
const motionPass = P.passes.motionPass;
const PASSES = P.config.passes;
const wants = (name) => !PASSES.length || PASSES.includes("all") || PASSES.includes(name);
const PAGES = ["installer", "npm-only"];

(async () => {
  const { acquireBrowser } = require(process.env.VALE_BROWSER_HELPER);
  const { page, close } = await acquireBrowser();
  const report = {
    rows: [], surfaces: [], names: [], focus: [], press: [], idle: [], hover: [], unstyled: [], motion: [],
    reflow: [], targets: [], themeChecks: [],
    entryCheck: (() => {
      try {
        const b = fs.readFileSync(EXPECTED_ENTRY_PATH);
        const c = crypto.createHash("sha256").update(b).digest("hex").slice(0, 12);
        return { bytes: b.length, sha: c, expected: EXPECTED_ENTRY, stale: b.length !== EXPECTED_ENTRY.bytes || c !== EXPECTED_ENTRY.sha };
      } catch (e) {
        return { error: String(e.message).slice(0, 60), expected: EXPECTED_ENTRY, stale: true };
      }
    })(),
  };
  await page.route("http://vale.test/**", (route) => {
    const p = new URL(route.request().url()).pathname;
    const file = p === "/" || p === "" ? "installer.html" : p.replace(/^\//, "");
    const full = path.join(ROOT, file);
    if (!fs.existsSync(full)) return route.fulfill({ status: 404, contentType: "text/plain", body: "not found" });
    const ext = path.extname(full);
    const type = ext === ".js" ? "text/javascript" : ext === ".css" ? "text/css" : ext === ".png" ? "image/png" : ext === ".svg" ? "image/svg+xml" : "text/html; charset=utf-8";
    return route.fulfill({ status: 200, contentType: type, headers: { "cache-control": "no-store" }, body: fs.readFileSync(full) });
  });
  for (const scheme of ["light", "dark"]) {
    await page.emulateMedia({ colorScheme: scheme });
    for (const label of PAGES) {
      await page.setViewportSize({ width: 1440, height: 900 });
      await page.goto("http://vale.test/" + label + ".html?cb=" + Date.now(), { waitUntil: "load" });
      await page.waitForTimeout(1200);
      const where = label + "@1440" + (scheme === "dark" ? "-dark" : "");
      report.themeChecks.push({ page: where, intended: scheme, scheme: await page.evaluate(() => matchMedia("(prefers-color-scheme: dark)").matches) });
      if (wants("contrast")) {
        const rows = await page.evaluate(PROBE);
        for (const r of rows) report.rows.push({ ...r, page: where, width: 1440, density: "landing", theme: scheme });
        report.surfaces.push({ page: where, width: 1440, theme: scheme, ...(await page.evaluate(SURFACE, SELECTOR)), marks: await page.evaluate(MARKS, SELECTOR) });
      }
      if (wants("names")) report.names.push({ page: where, ...(await page.evaluate(NAMES, SELECTOR)) });
      if (wants("focus")) report.focus.push(await focusPass(page, 14, { page: where, width: 1440 }));
      if (wants("idle")) {
        const idle = await idlePass(page, 6000);
        report.idle.push({ page: where, width: 1440, density: "landing", theme: scheme, seconds: 6, ...idle });
      }
      if (wants("unstyled")) report.unstyled.push({ page: where, ...(await page.evaluate(UNSTYLED)) });
      if (wants("targets")) report.targets.push({ page: where, width: 1440, ...(await page.evaluate(TARGETS)) });
      if (wants("press")) {
        const rows = await pressPass(page, [".btn-primary", "a", ".theme-toggle"], { page: where, width: 1440 });
        report.press.push({ page: where, width: 1440, density: "landing", theme: scheme, measured: rows.filter((r) => !r.note).length, rows });
      }
    }
  }
  if (wants("reflow")) {
    for (const width of [640, 320]) {
      await page.setViewportSize({ width, height: 800 });
      for (const label of PAGES) {
        await page.goto("http://vale.test/" + label + ".html?cb=" + Date.now(), { waitUntil: "load" });
        await page.waitForTimeout(900);
        report.reflow.push({ page: label + "@" + width, width, density: "landing", theme: "light", ...(await page.evaluate(REFLOW, SELECTOR)) });
      }
    }
  }
  if (wants("motion")) {
    report.motion.push(await motionPass(page, async () => {
      await page.goto("http://vale.test/installer.html?cb=" + Date.now(), { waitUntil: "load" });
      await page.waitForTimeout(1500);
    }, { page: "installer", width: 1440, density: "landing", theme: "light" }));
  }
  fs.writeFileSync(REPORT_PATH, JSON.stringify(report));
  console.log(JSON.stringify({ rows: report.rows.length, surfaces: report.surfaces.length, names: report.names.length, press: report.press.length }));
  await close();
})().catch((e) => {
  console.error("FATAL " + String(e && e.message).slice(0, 200));
  process.exit(1);
});
