//! `server/routing.mjs` — pure URL routing and the entry plumbing helpers around it.
//!
//! WHY THIS IS THE FIRST PIECE OF THE RELAY TO MOVE. The module's own header says it: it is "pure URL
//! routing + entry plumbing helpers for the VPS entry", it has its own test file
//! (`server/test/routing.test.mjs`, written in SOLID round 18 because the whole `api-relay` tree had
//! zero tests), and it is what was left in `entry.mjs` once the socket plumbing was separated from the
//! decisions. It needs no socket, no fetch and no runtime — so it is provable here, in `cargo test`,
//! long before the axum binary exists.
//!
//! THE ROUTING TABLE REPLAYS A FILE THAT IS GONE. `vercel.json` was deleted when Vercel was retired
//! (2026-09-08), so `entry.mjs`'s `ROUTES` and this port ARE the semantics — there is nothing else to
//! consult. What must never regress, in the JavaScript suite's own words: **`/api/git` vs `/api/github`
//! disambiguation** (a naive `startsWith` routes github traffic to the git handler), exact-prefix
//! matches, query preservation for git's smart-http (`service=git-upload-pack`), and dropping a
//! caller-supplied `path=` that would collide with the rewritten one.
//!
//! # WHAT PROVES IT
//!
//! `fixtures/routing-corpus.json` holds inputs and the OUTPUT THE SHIPPING JAVASCRIPT PRODUCED for
//! them — generated by `oracle.mjs`, which imports `server/routing.mjs` itself — and
//! `tests::the_typescript_corpus` replays every case here. It runs in the `proxies` job's
//! `cargo test --manifest-path proxies/api-relay/relay/Cargo.toml`, so the equivalence is re-checked on
//! every push rather than recorded once in a commit message. The JavaScript suite
//! (`node --test` in `proxies/api-relay`) stays green beside it: it is the ORACLE now, and it is the
//! half that stops being the implementation.

use serde_json::{Map, Value};

/// `resolveHost(headers)` — the REAL public host, with `x-forwarded-host` first.
///
/// nginx fronts the relay (`location /api/ -> 127.0.0.1:8081`, Host preserved), so a request's own
/// origin is `https://<public host>`; gform's body rewriting builds proxy URLs from that origin and must
/// see the real host rather than the loopback one.
pub fn resolve_host(headers: &Map<String, Value>) -> Value {
    // `headers["x-forwarded-host"] || headers.host || "localhost"` — TRUTHINESS at each step, so an
    // EMPTY x-forwarded-host falls through to `host` and an empty host falls through to the default.
    for key in ["x-forwarded-host", "host"] {
        if let Some(v) = headers.get(key) {
            // TRUTHINESS, not "is the text non-empty": `null` is FALSY, so
            // `{"x-forwarded-host": null, host: "api.saisi.online"}` answers the host — and the first
            // version of this port returned the string `"null"`, which the fixture caught. An empty
            // ARRAY is truthy and stringifies to `""`, which is the other half of the same rule.
            if truthy(v) {
                // THE RAW VALUE, NOT ITS TEXT: `headers["x-forwarded-host"] || headers.host` returns
                // whatever it found, so a NUMBER or an ARRAY is the answer — and `JSON.stringify` of it
                // is what the fixture carries. The coercion happens where the host is USED, in
                // `build_url`'s template, which is exactly where the JavaScript does it.
                return v.clone();
            }
        }
    }
    Value::String("localhost".to_string())
}

/// JavaScript TRUTHINESS for a JSON value — `false` for `null`, `false`, `0`, `NaN` and `""`, and
/// `true` for every array and object (an EMPTY one included).
fn truthy(v: &Value) -> bool {
    match v {
        Value::Null => false,
        Value::Bool(b) => *b,
        Value::Number(n) => n.as_f64().is_some_and(|f| f != 0.0 && !f.is_nan()),
        Value::String(s) => !s.is_empty(),
        Value::Array(_) | Value::Object(_) => true,
    }
}

/// `${v}` — the template coercion. A header value is normally a string; an ARRAY reaches here because
/// Node's `rawHeaders`-shaped objects carry multi-values as arrays, and `String([a, b])` is `"a,b"`.
fn js_text(v: &Value) -> String {
    match v {
        Value::Null => "null".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => s.clone(),
        Value::Array(items) => items
            .iter()
            .map(|i| match i {
                Value::Null => String::new(),
                other => js_text(other),
            })
            .collect::<Vec<_>>()
            .join(","),
        Value::Object(_) => "[object Object]".to_string(),
    }
}

/// One entry of the routes table: `{ prefix, handler, pathFromRest? }`. `handler` stays an OPAQUE
/// value — `resolveRoute` never calls it, and in the JavaScript the real functions exist only in
/// `dist/`, which is why the test file passes a synthetic table.
#[derive(Debug, Clone, PartialEq)]
pub struct Route {
    pub prefix: String,
    pub handler: Value,
    pub path_from_rest: bool,
}

/// A route hit: the route, the pathname and the search string (WITHOUT its `?`).
#[derive(Debug, Clone, PartialEq)]
pub struct Hit {
    pub route: Route,
    pub pathname: String,
    pub search: String,
}

/// `resolveRoute(routes, rawUrl)` — the FIRST route whose prefix matches, or nothing.
///
/// THE SEPARATOR IS THE WHOLE POINT: `pathname === r.prefix || pathname.startsWith(r.prefix + "/")`,
/// so `/api/gitx` matches NOTHING and `/api/git/…` does not become `/api/github/…` by a prefix test.
pub fn resolve_route(routes: &[Route], raw_url: &str) -> Option<Hit> {
    let qmark = raw_url.find('?');
    let (pathname, search) = match qmark {
        Some(i) => (&raw_url[..i], &raw_url[i + 1..]),
        None => (raw_url, ""),
    };
    for r in routes {
        if pathname == r.prefix || pathname.starts_with(&format!("{}/", r.prefix)) {
            return Some(Hit {
                route: r.clone(),
                pathname: pathname.to_string(),
                search: search.to_string(),
            });
        }
    }
    None
}

/// `buildUrl({ r, pathname, search }, host)` — the upstream Request URL for a route hit.
///
/// A `pathFromRest` route FOLDS THE TAIL INTO A `path` QUERY PARAM, which is the shape the deleted
/// `vercel.json` declared as `"/api/git/:path*" -> "/api/git?path=/:path*"`. The original query args are
/// preserved — git's smart-http needs `service=git-upload-pack` — and a caller-supplied `path=` is
/// DROPPED, because it would collide with the rewritten one.
pub fn build_url(hit: &Hit, host: &Value) -> String {
    let host = js_text(host);
    let host = host.as_str();
    let r = &hit.route;
    if !r.path_from_rest {
        return format!(
            "https://{host}{}{}",
            hit.pathname,
            if hit.search.is_empty() {
                String::new()
            } else {
                format!("?{}", hit.search)
            }
        );
    }
    let rest = &hit.pathname[r.prefix.len()..];
    // `"/" + rest.replace(/^\//, "")` — the leading slash is dropped and exactly one is put back.
    let path = format!("/{}", rest.strip_prefix('/').unwrap_or(rest));
    let mut params = FormParams::new();
    params.set("path", &path);
    if !hit.search.is_empty() {
        for (k, v) in FormParams::parse(&hit.search).entries() {
            if k != "path" {
                params.append(&k, &v);
            }
        }
    }
    format!("https://{host}{}?{params}", r.prefix)
}

/// `URLSearchParams` — the application/x-www-form-urlencoded codec, which is what `toString()` emits
/// and what the constructor parses.
///
/// IT IS A CODEC RATHER THAN A STRING JOIN, and the corpus is why: a space is `+` on the way out and
/// `+` is a space on the way in, `%2F` decodes to `/` and is re-encoded as `%2F`, and a `%` that is not
/// followed by two hex digits is left LITERAL (the spec's forgiving decode) rather than raising.
#[derive(Default)]
pub struct FormParams(Vec<(String, String)>);

impl FormParams {
    pub fn new() -> Self {
        FormParams(Vec::new())
    }

    /// `params.set(k, v)` — the spec's rule: the FIRST pair with that name takes the value and every
    /// LATER one is removed; if there is none, a pair is appended. (The first version of this walked
    /// the list with a `retain` that compared pointers, which is not a rule at all.)
    pub fn set(&mut self, k: &str, v: &str) {
        let mut found = false;
        let mut out: Vec<(String, String)> = Vec::new();
        for (name, value) in std::mem::take(&mut self.0) {
            if name == k {
                if !found {
                    out.push((name, v.to_string()));
                    found = true;
                }
            } else {
                out.push((name, value));
            }
        }
        if !found {
            out.push((k.to_string(), v.to_string()));
        }
        self.0 = out;
    }

    pub fn append(&mut self, k: &str, v: &str) {
        self.0.push((k.to_string(), v.to_string()));
    }

    pub fn entries(&self) -> Vec<(String, String)> {
        self.0.clone()
    }

    /// `new URLSearchParams(search)` — split on `&`, then on the FIRST `=`, then decode both halves.
    /// An empty input has NO entries (not one empty pair), which is what the spec says.
    pub fn parse(search: &str) -> Self {
        let mut out = FormParams::new();
        if search.is_empty() {
            return out;
        }
        for pair in search.split('&') {
            let (k, v) = match pair.find('=') {
                Some(i) => (&pair[..i], &pair[i + 1..]),
                None => (pair, ""),
            };
            out.0.push((form_decode(k), form_decode(v)));
        }
        out
    }
}

/// `URLSearchParams.prototype.toString()` — `k=v&k=v`, each half percent-encoded with the urlencoded
/// set. It is `Display` rather than an inherent `to_string`, which is what `clippy` asked for and what
/// the callers want anyway.
impl std::fmt::Display for FormParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let joined = self
            .0
            .iter()
            .map(|(k, v)| format!("{}={}", form_encode(k), form_encode(v)))
            .collect::<Vec<_>>()
            .join("&");
        write!(f, "{joined}")
    }
}

/// The `application/x-www-form-urlencoded` DECODE: `+` is a space, `%XX` is a byte, and anything else
/// (including a `%` with no two hex digits after it) is literal. Bytes are then read as UTF-8, with
/// invalid sequences replaced — which is what the `USVString` conversion does.
pub fn form_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out: Vec<u8> = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b'%' if i + 2 < bytes.len() => {
                let hex = |c: u8| (c as char).to_digit(16);
                match (hex(bytes[i + 1]), hex(bytes[i + 2])) {
                    (Some(hi), Some(lo)) => {
                        out.push((hi * 16 + lo) as u8);
                        i += 3;
                    }
                    _ => {
                        out.push(b'%');
                        i += 1;
                    }
                }
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).to_string()
}

/// The urlencoded ENCODE: everything except `A-Za-z0-9*-._` is percent-encoded, and a space is `+`.
pub fn form_encode(s: &str) -> String {
    let mut out = String::new();
    for b in s.as_bytes() {
        match b {
            b' ' => out.push('+'),
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'*' | b'-' | b'.' | b'_' => {
                out.push(*b as char)
            }
            other => out.push_str(&format!("%{other:02X}")),
        }
    }
    out
}

// ── THE HEADER PLUMBING (`forwardHeaders` · `collectResponseHeaders`) ─────────────────────────────
//
// These two decide what rides upstream and what rides back, and they are WHATWG `Headers` semantics
// rather than a dictionary: names are LOWERCASED and validated as HTTP tokens, values are trimmed of
// HTTP whitespace and validated, iteration is SORTED BY NAME, and multiple values COMBINE — with `; `
// for `cookie` (the spec's own special case, so a session cookie is not torn apart by a comma) and
// `, ` for everything else. `set-cookie` is NOT combined: it rides as one entry per value, which is
// exactly why `collect_response_headers` puts the array back.

/// The HTTP whitespace a header value is trimmed of: SP, HT, LF, CR.
fn trim_http_whitespace(s: &str) -> &str {
    s.trim_matches(|c| matches!(c, ' ' | '\t' | '\n' | '\r'))
}

/// An HTTP token (RFC 9110): `!#$%&'*+-.^_`|~` and the alphanumerics. A name outside this set is a
/// TypeError in the `Headers` API, and the corpus carries one.
fn is_token(s: &str) -> bool {
    !s.is_empty()
        && s.bytes().all(|b| {
            b.is_ascii_alphanumeric()
                || matches!(
                    b,
                    b'!' | b'#'
                        | b'$'
                        | b'%'
                        | b'&'
                        | b'\''
                        | b'*'
                        | b'+'
                        | b'-'
                        | b'.'
                        | b'^'
                        | b'_'
                        | b'`'
                        | b'|'
                        | b'~'
                )
        })
}

/// A header value may not carry NUL, LF or CR — `Headers` raises, and this is the check that says so
/// rather than writing a header that would split the request.
///
/// **AND IT MUST BE A BYTE STRING**: every code point at or below U+00FF. `new Headers().set("x", "中")`
/// is a TypeError ("Cannot convert argument to a ByteString… greater than 255"), which the corpus found
/// by carrying one — a port that accepted it would put a header on the wire that no `Headers` object
/// would ever have produced.
fn is_valid_value(s: &str) -> bool {
    !s.contains('\0')
        && !s.contains('\n')
        && !s.contains('\r')
        && s.chars().all(|c| (c as u32) <= 0xFF)
}

/// `forwardHeaders(rawHeaders)` — the inbound headers for the upstream Request.
///
/// Drops hop-by-hop noise (`host`, which is rebuilt from the upstream URL, and HTTP/2 pseudo-headers)
/// and returns the header LIST the way `[...headers.entries()]` reads it: lowercased names, sorted,
/// multi-values combined. The first version of this port returned a map and lost both the order and the
/// combining, which the corpus would have caught on its first set-cookie case.
pub fn forward_headers(raw: &Map<String, Value>) -> Result<Vec<(String, String)>, String> {
    let mut list: Vec<(String, String)> = Vec::new();
    for (k, v) in raw {
        if k == "host" || k.starts_with(':') {
            continue;
        }
        let values: Vec<Value> = match v {
            Value::Array(items) => items.clone(),
            other => vec![other.clone()],
        };
        let multi = matches!(v, Value::Array(_));
        for one in values {
            let name = k.to_lowercase();
            if !is_token(&name) {
                return Err(format!("invalid header name: {k:?}"));
            }
            let value = trim_http_whitespace(&js_text(&one)).to_string();
            if !is_valid_value(&value) {
                return Err(format!("invalid header value for {name:?}"));
            }
            if multi {
                list.push((name, value));
            } else {
                // `headers.set(k, v)` REPLACES every existing entry — and since an object cannot repeat
                // a key, that only differs from `append` when the name collides after LOWERCASING.
                list.retain(|(n, _)| n != &name);
                list.push((name, value));
            }
        }
    }
    Ok(combine(list))
}

/// The spec's sort-and-combine: sorted by name, one entry per name — except `set-cookie`, which rides
/// as one entry PER VALUE — with `cookie` joined by `; ` and everything else by `, `.
fn combine(list: Vec<(String, String)>) -> Vec<(String, String)> {
    let mut names: Vec<String> = Vec::new();
    for (n, _) in &list {
        if !names.contains(n) {
            names.push(n.clone());
        }
    }
    names.sort();
    let mut out = Vec::new();
    for name in names {
        let values: Vec<String> = list
            .iter()
            .filter(|(n, _)| n == &name)
            .map(|(_, v)| v.clone())
            .collect();
        if name == "set-cookie" {
            for v in values {
                out.push((name.clone(), v));
            }
        } else {
            let sep = if name == "cookie" { "; " } else { ", " };
            out.push((name, values.join(sep)));
        }
    }
    out
}

/// `collectResponseHeaders(response)` — the plain-object headers for the `node:http` reply.
///
/// `entries` is the upstream's combined list and `set_cookie` its `getSetCookie()` values: multi
/// set-cookie values ride as an ARRAY, because gform's reCAPTCHA session needs ALL of them rather than
/// the first.
///
/// **`content-length` AND `content-encoding` ARE DROPPED ON PURPOSE, AND IT IS A CORRECTNESS FIX RATHER
/// THAN TIDINESS** (the JavaScript's own note, round 126): `fetch` TRANSPARENTLY DECOMPRESSES the body
/// and leaves both headers exactly as the upstream sent them, so forwarding them makes the reply a lie
/// — a length that is no longer the length and a `gzip` over bytes that are no longer compressed. It is
/// reachable rather than theoretical, because `forward_headers` passes the CALLER's `accept-encoding`
/// upstream.
pub fn collect_response_headers(entries: &[(String, String)], set_cookie: &[String]) -> Value {
    let mut out = Map::new();
    for (k, v) in entries {
        // `Object.fromEntries` keeps the LAST value for a repeated key, and a numeric-looking key would
        // jump to the front of a JavaScript object — header names are neither.
        out.insert(k.clone(), Value::String(v.clone()));
    }
    if !set_cookie.is_empty() {
        out.insert(
            "set-cookie".to_string(),
            Value::Array(
                set_cookie
                    .iter()
                    .map(|v| Value::String(v.clone()))
                    .collect(),
            ),
        );
    }
    out.remove("content-length");
    out.remove("content-encoding");
    Value::Object(out)
}

// ── `/api/proxy`'s DECISIONS: the CORS copy and the upstream request plan ─────────────────────────
//
// BYOK-ONLY, AND DEFAULT-CLOSED. The caller MUST supply their own OpenRouter key in `Authorization`;
// there is no built-in env key to spend, so a request without one is refused with 401 rather than
// relayed. And any Origin outside the allowlist gets NO `Access-Control-Allow-Origin` header at all —
// absence is the refusal, which is why the corpus pins `null` rather than a string.

/// The console origins this relay serves. The gateway's `http.ts` holds the same closed set, and
/// `proxy-gate.test.mjs` is the test that keeps the two copies equal.
const ALLOWED_ORIGINS: [&str; 2] = ["https://ai.saisi.online", "https://api.saisi.online"];

/// The headers `/api/proxy` will forward upstream. Anything else the caller sends is DROPPED — the
/// list is an allowlist, not a filter.
const SAFE: [&str; 6] = [
    "accept",
    "accept-encoding",
    "accept-language",
    "anthropic-version",
    "content-type",
    "user-agent",
];

/// `new URL(request.url).hostname`, with `""` for a URL that does not parse — the JavaScript's `catch`.
pub fn request_host(url: &str) -> String {
    url::Url::parse(url)
        .ok()
        .and_then(|u| u.host_str().map(|h| h.to_string()))
        .unwrap_or_default()
}

/// A loopback Origin is a LOCAL-DEV affordance, not a production grant: `http:`/`https:` on
/// `localhost` or `127.0.0.1`.
pub fn is_loopback_origin(origin: &str) -> bool {
    match url::Url::parse(origin) {
        Ok(u) => {
            matches!(u.scheme(), "http" | "https")
                && matches!(u.host_str(), Some("localhost") | Some("127.0.0.1"))
        }
        Err(_) => false,
    }
}

/// `corsHeaders(request)` — the object the handler spreads into every reply.
///
/// **THE LOOPBACK RULE IS THE TRAP THIS KEEPS CLOSED**: a loopback Origin is reflected only when the
/// REQUEST HOST is itself loopback, so the deployed relay never reflects a foreign page's
/// `http://localhost` Origin. The corpus carries that pair both ways.
pub fn cors_headers(origin: &str, request_host: &str) -> Vec<(String, String)> {
    let mut out = vec![
        (
            "Access-Control-Allow-Methods".to_string(),
            "GET,POST,OPTIONS".to_string(),
        ),
        ("Access-Control-Allow-Headers".to_string(), "*".to_string()),
    ];
    let loopback_host = matches!(request_host, "localhost" | "127.0.0.1");
    if ALLOWED_ORIGINS.contains(&origin) || (is_loopback_origin(origin) && loopback_host) {
        out.push((
            "Access-Control-Allow-Origin".to_string(),
            origin.to_string(),
        ));
        out.push(("Vary".to_string(), "Origin".to_string()));
    }
    out
}

/// What the handler decided to do with a request.
#[derive(Debug, Clone, PartialEq)]
pub enum ProxyPlan {
    /// `OPTIONS` SHORT-CIRCUITS BEFORE THE GATE: the reply is the CORS object and nothing else — no
    /// authorization check, no upstream call. The corpus found this by carrying an `OPTIONS` request
    /// WITH a caller key: the JavaScript answered 200 and never dialled, and the first version of this
    /// port planned an upstream request for it.
    Preflight,
    /// The 401 the caller gets, with the JSON body the JavaScript writes.
    Refused { status: u16, error: String },
    /// What rides upstream, in order, and whether a body goes with it.
    Send {
        headers: Vec<(String, String)>,
        send_body: bool,
    },
}

/// `handler`'s request half: which headers ride upstream, or the refusal.
///
/// THE ORDER OF THE THREE WRITES MATTERS AND IS THE JAVASCRIPT'S: the allowlist is copied first, then
/// `Authorization`, then `Content-Type` — which OVERRIDES a caller's own `content-type`, even though
/// `content-type` is in the allowlist — and finally the `anthropic-version` default, only if the
/// caller did not supply one.
pub fn proxy_upstream_plan(method: &str, headers: &Map<String, Value>) -> ProxyPlan {
    if method == "OPTIONS" {
        return ProxyPlan::Preflight;
    }
    let get = |name: &str| -> Option<String> {
        // `request.headers.get(n)` IS CASE-INSENSITIVE, and the harness passes the request's headers as
        // a plain object — so the lookup folds the name rather than trusting the caller's spelling.
        headers
            .iter()
            .find(|(k, _)| k.to_lowercase() == name)
            .map(|(_, v)| js_text(v))
    };
    let mut out: Vec<(String, String)> = Vec::new();
    for name in SAFE {
        // `if (v)` — TRUTHINESS, so an empty header is not forwarded as an empty header.
        if let Some(v) = get(name) {
            if !v.is_empty() {
                out.push((name.to_string(), v));
            }
        }
    }
    let Some(client_auth) = get("authorization").filter(|v| !v.is_empty()) else {
        return ProxyPlan::Refused {
            status: 401,
            error: "caller Authorization required (BYOK)".to_string(),
        };
    };
    // THE NAMES ARE LOWERCASED AND THE LIST IS SORTED, because that is what `Headers.set` and
    // `[...headers.entries()]` do — and the corpus reads the upstream request exactly that way. The
    // first version kept the caller's capitalisation and the insertion order, which is a different
    // observable value for the same request.
    out.push(("authorization".to_string(), client_auth));
    out.retain(|(k, _)| k != "content-type");
    out.push(("content-type".to_string(), "application/json".to_string()));
    if !out.iter().any(|(k, _)| k == "anthropic-version") {
        out.push(("anthropic-version".to_string(), "2023-06-01".to_string()));
    }
    ProxyPlan::Send {
        headers: combine(out),
        // GET/HEAD carry no body: passing one throws on some runtimes, so only methods with a body send
        // one — and `includes` is an EXACT, case-sensitive comparison.
        send_body: matches!(method, "POST" | "PUT" | "PATCH"),
    }
}

// ── THE `api/git` GATE'S TWO DECISIONS (`validPath` · `allowedRedirect`) ─────────────────────────
//
// THE SMART-HTTP RELAY'S SECURITY SURFACE, and both halves are STRICTER than the github handler's on
// purpose: the redirect allowlist here is `github.com` EXACTLY (no asset hosts, no `www`), and the path
// is checked BOTH as written and after PERCENT-DECODING — because `%2e%2e%2f` is a `..` that a
// written-form check never sees.

/// `decodeURIComponent(value)`: `%XX` is a byte, the bytes are read as UTF-8, and **ANY malformed input
/// is an ERROR** — a `%` with no two hex digits after it, or bytes that are not UTF-8.
///
/// IT IS NOT `form_decode`: `+` is a PLUS here rather than a space, and `form_decode` answers a lossy
/// replacement where this raises. The TypeScript's `try/catch` around `decodeURIComponent` is the
/// `Result` this returns.
fn decode_uri_component(s: &str) -> Result<String, ()> {
    let bytes = s.as_bytes();
    let mut out: Vec<u8> = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' {
            if i + 2 >= bytes.len() {
                return Err(());
            }
            let hex = |c: u8| (c as char).to_digit(16);
            match (hex(bytes[i + 1]), hex(bytes[i + 2])) {
                (Some(hi), Some(lo)) => {
                    out.push((hi * 16 + lo) as u8);
                    i += 3;
                }
                _ => return Err(()),
            }
        } else {
            out.push(bytes[i]);
            i += 1;
        }
    }
    // STRICT UTF-8, because `decodeURIComponent` raises a URIError on a byte sequence that is not.
    String::from_utf8(out).map_err(|_| ())
}

/// `validPath(value)` — is this a rooted, clean path the relay may build an upstream URL from?
///
/// `//host` IS PROTOCOL-RELATIVE: it passes a "starts with /" test and then REPLACES THE ORIGIN in
/// `new URL(path, base)`. That is why the shape is refused here as well as after decoding.
pub fn valid_path(value: &str) -> bool {
    if value.is_empty()
        || !value.starts_with('/')
        || value.contains('\\')
        || value.contains('\0')
        || value.contains("..")
    {
        return false;
    }
    if value.starts_with("//") {
        return false;
    }
    let Ok(decoded) = decode_uri_component(value) else {
        return false;
    };
    decoded.starts_with('/')
        && !decoded.starts_with("//")
        && !decoded.contains('\\')
        && !decoded.contains("..")
        // `/[\0-\x1f]/` — the CONTROL CHARACTERS, and note the range stops at 0x1F: `\x7f` (DEL) is
        // not one of them, which the JavaScript suite pins with `/a\x7fb`.
        && !decoded.chars().any(|c| (c as u32) <= 0x1F)
}

/// `allowedRedirect(location, current)` — the redirect the relay will follow, or nothing.
///
/// **`github.com` EXACTLY.** `www.github.com` and `objects.githubusercontent.com` are both refused
/// here, where the github handler allows the asset hosts it needs. `https:` only, and a RELATIVE
/// location is resolved against the current URL, which is what `new URL(location, current)` does.
pub fn allowed_redirect(location: &str, current: &str) -> Option<String> {
    if location.is_empty() {
        return None;
    }
    let base = url::Url::parse(current).ok()?;
    let target = base.join(location).ok()?;
    if target.scheme() == "https" && target.host_str() == Some("github.com") {
        Some(target.to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn routes() -> Vec<Route> {
        [
            ("/api/zen", false),
            ("/api/proxy", false),
            ("/api/github", true),
            ("/api/git", true),
            ("/api/gform", true),
        ]
        .iter()
        .map(|(prefix, path_from_rest)| Route {
            prefix: (*prefix).to_string(),
            handler: json!(prefix),
            path_from_rest: *path_from_rest,
        })
        .collect()
    }

    /// THE FIXTURE IS THE EQUIVALENCE PROOF, and it runs in CI: every case in
    /// `fixtures/routing-corpus.json` was produced by the SHIPPING `server/routing.mjs`
    /// (`oracle.mjs` drove it), and this replays them here.
    ///
    /// MUTATION: change one character of one case's expected `url` in the fixture.
    /// RESULT:   fails, naming the case and showing both strings.
    #[test]
    fn the_typescript_corpus() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/routing-corpus.json");
        let raw = std::fs::read_to_string(path).expect("the fixture is committed");
        let doc: Value = serde_json::from_str(&raw).expect("the fixture is JSON");
        let table: Vec<Route> = doc["routes"]
            .as_array()
            .expect("a routes array")
            .iter()
            .map(|r| Route {
                prefix: r["prefix"].as_str().unwrap_or("").to_string(),
                handler: r["handler"].clone(),
                path_from_rest: r["pathFromRest"].as_bool().unwrap_or(false),
            })
            .collect();

        let mut hosts = 0usize;
        for case in doc["hosts"].as_array().expect("a hosts array") {
            let headers = case["headers"]
                .as_object()
                .expect("a headers object")
                .clone();
            let want = &case["host"];
            assert_eq!(&resolve_host(&headers), want, "resolveHost({headers:?})");
            hosts += 1;
        }

        let mut routed = 0usize;
        for case in doc["routes_cases"]
            .as_array()
            .expect("a routes_cases array")
        {
            let raw_url = case["rawUrl"].as_str().expect("a rawUrl");
            let got = resolve_route(&table, raw_url);
            match (got, case["hit"].as_object()) {
                (None, None) => {}
                (Some(hit), Some(want)) => {
                    assert_eq!(
                        hit.route.prefix,
                        want["prefix"].as_str().unwrap_or(""),
                        "resolveRoute({raw_url:?}) prefix"
                    );
                    assert_eq!(
                        hit.pathname,
                        want["pathname"].as_str().unwrap_or(""),
                        "pathname"
                    );
                    assert_eq!(hit.search, want["search"].as_str().unwrap_or(""), "search");
                    // And the URL that hit builds, which is what the caller actually sends.
                    let host = &case["host"];
                    assert_eq!(
                        build_url(&hit, host),
                        case["url"].as_str().unwrap_or(""),
                        "buildUrl({raw_url:?}, {host:?})"
                    );
                    routed += 1;
                }
                (got, want) => panic!("resolveRoute({raw_url:?}): got {got:?}, want {want:?}"),
            }
        }
        assert!(hosts >= 8, "the fixture moved: only {hosts} host case(s)");
        assert!(
            routed >= 20,
            "the fixture moved: only {routed} routed case(s)"
        );
    }

    /// THE HEADER PLUMBING'S CORPUS, generated the same way: `oracle.mjs headers` drove the shipping
    /// `forwardHeaders`/`collectResponseHeaders` and this replays what they produced — including the
    /// five inputs the `Headers` API REFUSES (an invalid token as a name, an empty name, a value with a
    /// newline, one with a NUL) and the set-cookie cases that are the reason this is not a dictionary.
    ///
    /// MUTATION: change one expected value in `fixtures/headers-corpus.json`.
    /// RESULT:   fails, naming the input and showing both lists.
    #[test]
    fn the_typescript_header_corpus() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/headers-corpus.json");
        let raw = std::fs::read_to_string(path).expect("the fixture is committed");
        let doc: Value = serde_json::from_str(&raw).expect("the fixture is JSON");

        let pairs = |v: &Value| -> Vec<(String, String)> {
            v.as_array()
                .expect("an entries array")
                .iter()
                .map(|p| {
                    (
                        p[0].as_str().unwrap_or("").to_string(),
                        p[1].as_str().unwrap_or("").to_string(),
                    )
                })
                .collect()
        };

        let mut forwarded = 0usize;
        let mut refused = 0usize;
        for case in doc["forward_cases"]
            .as_array()
            .expect("a forward_cases array")
        {
            let headers = case["raw"].as_object().expect("a raw headers object");
            match forward_headers(headers) {
                Ok(list) => {
                    assert!(
                        case["threw"].is_null(),
                        "forwardHeaders({headers:?}) raised in the JavaScript and not here"
                    );
                    assert_eq!(list, pairs(&case["entries"]), "forwardHeaders({headers:?})");
                    forwarded += 1;
                }
                Err(message) => {
                    assert!(
                        case["threw"].is_string(),
                        "forwardHeaders({headers:?}) raised here ({message}) and not in the JavaScript"
                    );
                    refused += 1;
                }
            }
        }

        let mut responses = 0usize;
        for case in doc["response_cases"]
            .as_array()
            .expect("a response_cases array")
        {
            let entries = pairs(&case["entries"]);
            let set_cookie: Vec<String> = case["setCookie"]
                .as_array()
                .expect("a setCookie array")
                .iter()
                .map(|v| v.as_str().unwrap_or("").to_string())
                .collect();
            let got = collect_response_headers(&entries, &set_cookie);
            let want = &case["out"];
            assert_eq!(&got, want, "collectResponseHeaders({entries:?})");
            // KEY ORDER TOO, because a plain object's order is observable and `Object.fromEntries`
            // decides it.
            let keys = |v: &Value| -> Vec<String> {
                v.as_object()
                    .expect("an object")
                    .keys()
                    .cloned()
                    .collect::<Vec<_>>()
            };
            assert_eq!(keys(&got), keys(want), "key order for {entries:?}");
            responses += 1;
        }

        assert!(
            forwarded >= 10 && refused >= 3 && responses >= 5,
            "the fixture moved: {forwarded} forwarded, {refused} refused, {responses} responses"
        );
    }

    /// `/api/proxy`'s DECISIONS, generated by `oracle.mjs proxy` driving the shipping handler with a
    /// STUBBED fetch — which is how the node suite reaches these gates too. What it decided is read off
    /// the upstream `init` it passed and off the reply it built.
    ///
    /// MUTATION: change one expected header in `fixtures/proxy-corpus.json`.
    /// RESULT:   fails, naming the origin/method and showing both lists.
    #[test]
    fn the_typescript_proxy_corpus() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/proxy-corpus.json");
        let raw = std::fs::read_to_string(path).expect("the fixture is committed");
        let doc: Value = serde_json::from_str(&raw).expect("the fixture is JSON");

        let mut allowed = 0usize;
        let mut refused_origin = 0usize;
        for case in doc["cors_cases"].as_array().expect("a cors_cases array") {
            let origin = case["origin"].as_str().unwrap_or("");
            // THE FIXTURE CARRIES THE URL'S HOST:PORT, because that is what builds the Request; the
            // JavaScript then reads `new URL(request.url).hostname` — port stripped — so the port goes
            // through `request_host` here too rather than being compared directly.
            let host = request_host(&format!(
                "https://{}/api/proxy",
                case["host"].as_str().unwrap_or("")
            ));
            let got: Vec<(String, String)> = cors_headers(origin, &host)
                .into_iter()
                .map(|(k, v)| (k.to_lowercase(), v))
                .collect();
            // The reply's headers are a `Headers` object, so the fixture is sorted and lowercased;
            // the port's object is in insertion order, so the comparison sorts BOTH.
            let want: Vec<(String, String)> = case["headers"]
                .as_array()
                .expect("a headers array")
                .iter()
                .map(|p| {
                    (
                        p[0].as_str().unwrap_or("").to_string(),
                        p[1].as_str().unwrap_or("").to_string(),
                    )
                })
                .collect();
            let mut got_sorted = got.clone();
            got_sorted.sort();
            let mut want_sorted = want.clone();
            want_sorted.sort();
            assert_eq!(got_sorted, want_sorted, "corsHeaders({origin:?}, {host:?})");
            if got.iter().any(|(k, _)| k == "access-control-allow-origin") {
                allowed += 1;
            } else {
                refused_origin += 1;
            }
        }

        let mut refused = 0usize;
        let mut sent = 0usize;
        for case in doc["proxy_cases"].as_array().expect("a proxy_cases array") {
            // A THROWING CASE WOULD BE UNREAD BY THE ARMS BELOW, so it is a loud failure rather than a
            // silently skipped one: the oracle records throws, and this corpus has none.
            assert!(
                case["threw"].is_null(),
                "the fixture carries a throw this test cannot read: {case}"
            );
            let method = case["method"].as_str().expect("a method");
            let headers = case["headers"].as_object().expect("a headers object");
            match proxy_upstream_plan(method, headers) {
                ProxyPlan::Preflight => {
                    assert_eq!(method, "OPTIONS", "only OPTIONS short-circuits");
                    assert_eq!(case["status"].as_u64(), Some(200), "the preflight status");
                    assert!(case["upstream"].is_null(), "the preflight never dials");
                }
                ProxyPlan::Refused { status, error } => {
                    assert_eq!(
                        status,
                        case["status"].as_u64().unwrap_or(0) as u16,
                        "status for {method} {headers:?}"
                    );
                    assert!(
                        case["upstream"].is_null(),
                        "the JavaScript dialled for {method}"
                    );
                    assert!(
                        error.contains("BYOK"),
                        "the refusal names the rule: {error}"
                    );
                    refused += 1;
                }
                ProxyPlan::Send {
                    headers: got,
                    send_body,
                } => {
                    let want: Vec<(String, String)> = case["upstream"]
                        .as_array()
                        .expect("an upstream array")
                        .iter()
                        .map(|p| {
                            (
                                p[0].as_str().unwrap_or("").to_string(),
                                p[1].as_str().unwrap_or("").to_string(),
                            )
                        })
                        .collect();
                    assert_eq!(got, want, "upstream headers for {method} {headers:?}");
                    assert_eq!(
                        send_body,
                        case["sendBody"].as_bool().unwrap_or(false),
                        "sendBody for {method}"
                    );
                    sent += 1;
                }
            }
        }
        assert!(
            allowed >= 3 && refused_origin >= 3 && refused >= 2 && sent >= 5,
            "the fixture moved: {allowed} allowed, {refused_origin} refused origins, {refused} refused, {sent} sent"
        );
    }

    /// THE `api/git` GATE'S CORPUS, generated by `oracle.mjs git` driving the shipping `api/git.ts`.
    ///
    /// MUTATION: change one expected value in `fixtures/git-corpus.json`.
    /// RESULT:   fails, naming the path or the (location, current) pair.
    #[test]
    fn the_typescript_git_corpus() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/git-corpus.json");
        let raw = std::fs::read_to_string(path).expect("the fixture is committed");
        let doc: Value = serde_json::from_str(&raw).expect("the fixture is JSON");

        let mut valid = 0usize;
        let mut refused = 0usize;
        for case in doc["path_cases"].as_array().expect("a path_cases array") {
            let value = case["value"].as_str().expect("a path");
            let want = case["ok"].as_bool().expect("a verdict");
            assert_eq!(valid_path(value), want, "validPath({value:?})");
            if want {
                valid += 1;
            } else {
                refused += 1;
            }
        }

        let mut allowed = 0usize;
        let mut none = 0usize;
        let mut unparseable = 0usize;
        for case in doc["redirect_cases"]
            .as_array()
            .expect("a redirect_cases array")
        {
            let current = case["current"].as_str().expect("a current URL");
            let location = case["location"].as_str().unwrap_or("");
            if case["threw"].is_string() {
                // THE THROW IS THE HARNESS'S, NOT THE FUNCTION'S: `allowedRedirect` takes an
                // already-parsed `URL`, so an unparseable `current` is the caller's error. The port
                // takes the string and answers `None`, which is the same verdict the caller reaches.
                assert!(
                    url::Url::parse(current).is_err(),
                    "a throw for a current URL that parses: {current:?}"
                );
                assert_eq!(allowed_redirect(location, current), None, "{current:?}");
                unparseable += 1;
                continue;
            }
            let got = allowed_redirect(location, current);
            match case["out"].as_str() {
                Some(want) => {
                    assert_eq!(
                        got.as_deref(),
                        Some(want),
                        "allowedRedirect({location:?}, {current:?})"
                    );
                    allowed += 1;
                }
                None => {
                    assert_eq!(got, None, "allowedRedirect({location:?}, {current:?})");
                    none += 1;
                }
            }
        }
        assert!(
            valid >= 8 && refused >= 10 && allowed >= 3 && none >= 10 && unparseable >= 1,
            "the fixture moved: {valid} valid, {refused} refused, {allowed} allowed, {none} none, {unparseable} unparseable"
        );
    }

    #[test]
    fn the_percent_decoded_form_is_what_makes_this_a_gate() {
        // `%2e%2e%2f` IS a `..` that a written-form check never sees, and `//host` replaces the origin
        // in `new URL(path, base)`. Both are refused in both forms.
        assert!(!valid_path("/%2e%2e/x"));
        assert!(!valid_path("/a/../b"));
        assert!(!valid_path("//evil.example/x"));
        assert!(!valid_path("/%2F%2Fevil.example/x"));
        assert!(!valid_path("/a%5Cb"));
        // A DOUBLE-ENCODED traversal is NOT a traversal — `%252e` decodes to the TEXT `%2e`, and the
        // relay then hands that to the upstream as a literal path segment.
        assert!(valid_path("/%252e%252e/x"));
        // And DEL is not in the control range, which the JavaScript suite pins deliberately.
        assert!(valid_path("/a\u{7f}b"));
        assert!(!valid_path("/a\u{1f}b"));
    }

    #[test]
    fn github_com_exactly_and_https_only() {
        let current = "https://github.com/o/r";
        assert_eq!(
            allowed_redirect("/o/r2", current).as_deref(),
            Some("https://github.com/o/r2")
        );
        assert_eq!(allowed_redirect("https://www.github.com/a", current), None);
        assert_eq!(
            allowed_redirect("https://objects.githubusercontent.com/a", current),
            None,
            "the asset hosts the GITHUB handler allows are refused here"
        );
        assert_eq!(allowed_redirect("http://github.com/a", current), None);
        assert_eq!(allowed_redirect("", current), None);
        assert_eq!(
            allowed_redirect("//github.com/a", current).as_deref(),
            Some("https://github.com/a"),
            "a protocol-relative location resolves to https on the same host"
        );
    }

    #[test]
    fn a_loopback_origin_is_only_reflected_by_a_loopback_host() {
        // THE TRAP THIS KEEPS CLOSED: a foreign page cannot get `http://localhost` reflected by the
        // deployed relay, because the request host has to be loopback too.
        let allows = |origin: &str, request_url: &str| {
            cors_headers(origin, &request_host(request_url))
                .iter()
                .any(|(k, _)| k == "Access-Control-Allow-Origin")
        };
        assert!(allows(
            "http://localhost:3000",
            "https://127.0.0.1:3000/api/proxy"
        ));
        assert!(!allows(
            "http://localhost:3000",
            "https://r.example/api/proxy"
        ));
        assert!(!allows(
            "https://evil.example",
            "https://r.example/api/proxy"
        ));
        assert!(allows(
            "https://ai.saisi.online",
            "https://r.example/api/proxy"
        ));
        // An allowed origin is allowed whatever the request host is; only the LOOPBACK rule is paired.
        assert!(allows(
            "https://api.saisi.online",
            "https://evil.example/api/proxy"
        ));
    }

    #[test]
    fn the_caller_key_rides_verbatim_and_x_api_key_never_does() {
        // `/api/zen` accepts `x-api-key`; THIS relay does not — Authorization only, which is the
        // difference the node suite pins.
        let mut headers = Map::new();
        headers.insert("authorization".to_string(), json!("Bearer sk-or-test"));
        headers.insert("x-api-key".to_string(), json!("sk-should-not-ride"));
        headers.insert("cookie".to_string(), json!("a=1"));
        let ProxyPlan::Send { headers: got, .. } = proxy_upstream_plan("POST", &headers) else {
            panic!("a caller key was supplied");
        };
        let names: Vec<&str> = got.iter().map(|(k, _)| k.as_str()).collect();
        assert_eq!(
            names,
            vec!["anthropic-version", "authorization", "content-type"],
            "only the allowlist rides"
        );
        assert_eq!(
            got.iter().find(|(k, _)| k == "authorization").unwrap().1,
            "Bearer sk-or-test"
        );
    }

    #[test]
    fn the_two_headers_that_would_make_the_reply_a_lie_are_dropped() {
        // The JavaScript's own note, round 126: `fetch` decompresses the body and leaves both headers as
        // the upstream sent them. This is the rule that stops the relay forwarding them.
        let entries = vec![
            ("content-length".to_string(), "45".to_string()),
            ("content-encoding".to_string(), "gzip".to_string()),
            ("content-type".to_string(), "application/json".to_string()),
        ];
        let out = collect_response_headers(&entries, &[]);
        let obj = out.as_object().expect("an object");
        assert!(!obj.contains_key("content-length"));
        assert!(!obj.contains_key("content-encoding"));
        assert_eq!(obj["content-type"], json!("application/json"));
    }

    #[test]
    fn a_cookie_is_joined_with_a_semicolon_and_anything_else_with_a_comma() {
        // The spec's own special case, and the node suite's assertion: `a=1; b=2`, not `a=1, b=2`.
        let mut raw = Map::new();
        raw.insert("cookie".to_string(), json!(["a=1", "b=2"]));
        raw.insert("x-multi".to_string(), json!(["1", "2"]));
        let list = forward_headers(&raw).expect("valid");
        assert_eq!(
            list,
            vec![
                ("cookie".to_string(), "a=1; b=2".to_string()),
                ("x-multi".to_string(), "1, 2".to_string()),
            ]
        );
    }

    #[test]
    fn the_separator_rule_is_what_keeps_git_and_github_apart() {
        // The JavaScript suite's own words: a naive `startsWith` routes github traffic to the git
        // handler. Both directions are pinned here.
        let table = routes();
        assert_eq!(
            resolve_route(&table, "/api/git").unwrap().route.prefix,
            "/api/git"
        );
        assert_eq!(
            resolve_route(&table, "/api/git/info/refs")
                .unwrap()
                .route
                .prefix,
            "/api/git"
        );
        assert_eq!(
            resolve_route(&table, "/api/github/o/r")
                .unwrap()
                .route
                .prefix,
            "/api/github"
        );
        assert!(resolve_route(&table, "/api/gitx").is_none());
        assert!(resolve_route(&table, "/api/githubx/y").is_none());
    }

    #[test]
    fn a_caller_supplied_path_is_dropped_and_the_rest_are_kept_in_order() {
        let table = routes();
        let hit = resolve_route(
            &table,
            "/api/git/info/refs?path=%2Fevil&service=git-upload-pack&a=1",
        )
        .expect("a hit");
        let url = build_url(&hit, &json!("api.saisi.online"));
        assert_eq!(
            url,
            "https://api.saisi.online/api/git?path=%2Finfo%2Frefs&service=git-upload-pack&a=1"
        );
    }
}
