//! `server/routing.mjs` — pure URL routing and the entry plumbing helpers around it.
//!
//! WHY THIS IS THE FIRST PIECE OF THE RELAY TO MOVE. The module's own header says it: it is "pure URL
//! routing + entry plumbing helpers for the VPS entry", it has its own test file
//! (`server/test/routing.test.mjs`, written in SOLID round 18 because the whole `api-relay` tree had
//! zero tests), and it is what was left in `entry.mjs` once the socket plumbing was separated from the
//! decisions. It needs no socket, no fetch and no runtime — so it is provable here, in `cargo test`,
//! long before the axum binary exists.
//!
//! THE ROUTING TABLE REPLAYS A FILE THAT IS GONE. `vercel.json` was deleted when Vercel was retired
//! (2026-09-08), so `entry.mjs`'s `ROUTES` and this port ARE the semantics — there is nothing else to
//! consult. What must never regress, in the JavaScript suite's own words: **`/api/git` vs `/api/github`
//! disambiguation** (a naive `startsWith` routes github traffic to the git handler), exact-prefix
//! matches, query preservation for git's smart-http (`service=git-upload-pack`), and dropping a
//! caller-supplied `path=` that would collide with the rewritten one.
//!
//! # WHAT PROVES IT
//!
//! `fixtures/routing-corpus.json` holds inputs and the OUTPUT THE SHIPPING JAVASCRIPT PRODUCED for
//! them — generated by `oracle.mjs`, which imports `server/routing.mjs` itself — and
//! `tests::the_typescript_corpus` replays every case here. It runs in the `proxies` job's
//! `cargo test --manifest-path proxies/api-relay/relay/Cargo.toml`, so the equivalence is re-checked on
//! every push rather than recorded once in a commit message. The JavaScript suite
//! (`node --test` in `proxies/api-relay`) stays green beside it: it is the ORACLE now, and it is the
//! half that stops being the implementation.

use serde_json::{Map, Value};

/// `resolveHost(headers)` — the REAL public host, with `x-forwarded-host` first.
///
/// nginx fronts the relay (`location /api/ -> 127.0.0.1:8081`, Host preserved), so a request's own
/// origin is `https://<public host>`; gform's body rewriting builds proxy URLs from that origin and must
/// see the real host rather than the loopback one.
pub fn resolve_host(headers: &Map<String, Value>) -> Value {
    // `headers["x-forwarded-host"] || headers.host || "localhost"` — TRUTHINESS at each step, so an
    // EMPTY x-forwarded-host falls through to `host` and an empty host falls through to the default.
    for key in ["x-forwarded-host", "host"] {
        if let Some(v) = headers.get(key) {
            // TRUTHINESS, not "is the text non-empty": `null` is FALSY, so
            // `{"x-forwarded-host": null, host: "api.saisi.online"}` answers the host — and the first
            // version of this port returned the string `"null"`, which the fixture caught. An empty
            // ARRAY is truthy and stringifies to `""`, which is the other half of the same rule.
            if truthy(v) {
                // THE RAW VALUE, NOT ITS TEXT: `headers["x-forwarded-host"] || headers.host` returns
                // whatever it found, so a NUMBER or an ARRAY is the answer — and `JSON.stringify` of it
                // is what the fixture carries. The coercion happens where the host is USED, in
                // `build_url`'s template, which is exactly where the JavaScript does it.
                return v.clone();
            }
        }
    }
    Value::String("localhost".to_string())
}

/// JavaScript TRUTHINESS for a JSON value — `false` for `null`, `false`, `0`, `NaN` and `""`, and
/// `true` for every array and object (an EMPTY one included).
fn truthy(v: &Value) -> bool {
    match v {
        Value::Null => false,
        Value::Bool(b) => *b,
        Value::Number(n) => n.as_f64().is_some_and(|f| f != 0.0 && !f.is_nan()),
        Value::String(s) => !s.is_empty(),
        Value::Array(_) | Value::Object(_) => true,
    }
}

/// `${v}` — the template coercion. A header value is normally a string; an ARRAY reaches here because
/// Node's `rawHeaders`-shaped objects carry multi-values as arrays, and `String([a, b])` is `"a,b"`.
fn js_text(v: &Value) -> String {
    match v {
        Value::Null => "null".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => s.clone(),
        Value::Array(items) => items
            .iter()
            .map(|i| match i {
                Value::Null => String::new(),
                other => js_text(other),
            })
            .collect::<Vec<_>>()
            .join(","),
        Value::Object(_) => "[object Object]".to_string(),
    }
}

/// One entry of the routes table: `{ prefix, handler, pathFromRest? }`. `handler` stays an OPAQUE
/// value — `resolveRoute` never calls it, and in the JavaScript the real functions exist only in
/// `dist/`, which is why the test file passes a synthetic table.
#[derive(Debug, Clone, PartialEq)]
pub struct Route {
    pub prefix: String,
    pub handler: Value,
    pub path_from_rest: bool,
}

/// A route hit: the route, the pathname and the search string (WITHOUT its `?`).
#[derive(Debug, Clone, PartialEq)]
pub struct Hit {
    pub route: Route,
    pub pathname: String,
    pub search: String,
}

/// `resolveRoute(routes, rawUrl)` — the FIRST route whose prefix matches, or nothing.
///
/// THE SEPARATOR IS THE WHOLE POINT: `pathname === r.prefix || pathname.startsWith(r.prefix + "/")`,
/// so `/api/gitx` matches NOTHING and `/api/git/…` does not become `/api/github/…` by a prefix test.
pub fn resolve_route(routes: &[Route], raw_url: &str) -> Option<Hit> {
    let qmark = raw_url.find('?');
    let (pathname, search) = match qmark {
        Some(i) => (&raw_url[..i], &raw_url[i + 1..]),
        None => (raw_url, ""),
    };
    for r in routes {
        if pathname == r.prefix || pathname.starts_with(&format!("{}/", r.prefix)) {
            return Some(Hit {
                route: r.clone(),
                pathname: pathname.to_string(),
                search: search.to_string(),
            });
        }
    }
    None
}

/// `buildUrl({ r, pathname, search }, host)` — the upstream Request URL for a route hit.
///
/// A `pathFromRest` route FOLDS THE TAIL INTO A `path` QUERY PARAM, which is the shape the deleted
/// `vercel.json` declared as `"/api/git/:path*" -> "/api/git?path=/:path*"`. The original query args are
/// preserved — git's smart-http needs `service=git-upload-pack` — and a caller-supplied `path=` is
/// DROPPED, because it would collide with the rewritten one.
pub fn build_url(hit: &Hit, host: &Value) -> String {
    let host = js_text(host);
    let host = host.as_str();
    let r = &hit.route;
    if !r.path_from_rest {
        return format!(
            "https://{host}{}{}",
            hit.pathname,
            if hit.search.is_empty() {
                String::new()
            } else {
                format!("?{}", hit.search)
            }
        );
    }
    let rest = &hit.pathname[r.prefix.len()..];
    // `"/" + rest.replace(/^\//, "")` — the leading slash is dropped and exactly one is put back.
    let path = format!("/{}", rest.strip_prefix('/').unwrap_or(rest));
    let mut params = FormParams::new();
    params.set("path", &path);
    if !hit.search.is_empty() {
        for (k, v) in FormParams::parse(&hit.search).entries() {
            if k != "path" {
                params.append(&k, &v);
            }
        }
    }
    format!("https://{host}{}?{params}", r.prefix)
}

/// `URLSearchParams` — the application/x-www-form-urlencoded codec, which is what `toString()` emits
/// and what the constructor parses.
///
/// IT IS A CODEC RATHER THAN A STRING JOIN, and the corpus is why: a space is `+` on the way out and
/// `+` is a space on the way in, `%2F` decodes to `/` and is re-encoded as `%2F`, and a `%` that is not
/// followed by two hex digits is left LITERAL (the spec's forgiving decode) rather than raising.
#[derive(Default)]
pub struct FormParams(Vec<(String, String)>);

impl FormParams {
    pub fn new() -> Self {
        FormParams(Vec::new())
    }

    /// `params.set(k, v)` — the spec's rule: the FIRST pair with that name takes the value and every
    /// LATER one is removed; if there is none, a pair is appended. (The first version of this walked
    /// the list with a `retain` that compared pointers, which is not a rule at all.)
    pub fn set(&mut self, k: &str, v: &str) {
        let mut found = false;
        let mut out: Vec<(String, String)> = Vec::new();
        for (name, value) in std::mem::take(&mut self.0) {
            if name == k {
                if !found {
                    out.push((name, v.to_string()));
                    found = true;
                }
            } else {
                out.push((name, value));
            }
        }
        if !found {
            out.push((k.to_string(), v.to_string()));
        }
        self.0 = out;
    }

    pub fn append(&mut self, k: &str, v: &str) {
        self.0.push((k.to_string(), v.to_string()));
    }

    pub fn entries(&self) -> Vec<(String, String)> {
        self.0.clone()
    }

    /// `new URLSearchParams(search)` — split on `&`, then on the FIRST `=`, then decode both halves.
    /// An empty input has NO entries (not one empty pair), which is what the spec says.
    pub fn parse(search: &str) -> Self {
        let mut out = FormParams::new();
        if search.is_empty() {
            return out;
        }
        for pair in search.split('&') {
            let (k, v) = match pair.find('=') {
                Some(i) => (&pair[..i], &pair[i + 1..]),
                None => (pair, ""),
            };
            out.0.push((form_decode(k), form_decode(v)));
        }
        out
    }
}

/// `URLSearchParams.prototype.toString()` — `k=v&k=v`, each half percent-encoded with the urlencoded
/// set. It is `Display` rather than an inherent `to_string`, which is what `clippy` asked for and what
/// the callers want anyway.
impl std::fmt::Display for FormParams {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let joined = self
            .0
            .iter()
            .map(|(k, v)| format!("{}={}", form_encode(k), form_encode(v)))
            .collect::<Vec<_>>()
            .join("&");
        write!(f, "{joined}")
    }
}

/// The `application/x-www-form-urlencoded` DECODE: `+` is a space, `%XX` is a byte, and anything else
/// (including a `%` with no two hex digits after it) is literal. Bytes are then read as UTF-8, with
/// invalid sequences replaced — which is what the `USVString` conversion does.
pub fn form_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out: Vec<u8> = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b'%' if i + 2 < bytes.len() => {
                let hex = |c: u8| (c as char).to_digit(16);
                match (hex(bytes[i + 1]), hex(bytes[i + 2])) {
                    (Some(hi), Some(lo)) => {
                        out.push((hi * 16 + lo) as u8);
                        i += 3;
                    }
                    _ => {
                        out.push(b'%');
                        i += 1;
                    }
                }
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).to_string()
}

/// The urlencoded ENCODE: everything except `A-Za-z0-9*-._` is percent-encoded, and a space is `+`.
pub fn form_encode(s: &str) -> String {
    let mut out = String::new();
    for b in s.as_bytes() {
        match b {
            b' ' => out.push('+'),
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'*' | b'-' | b'.' | b'_' => {
                out.push(*b as char)
            }
            other => out.push_str(&format!("%{other:02X}")),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn routes() -> Vec<Route> {
        [
            ("/api/zen", false),
            ("/api/proxy", false),
            ("/api/github", true),
            ("/api/git", true),
            ("/api/gform", true),
        ]
        .iter()
        .map(|(prefix, path_from_rest)| Route {
            prefix: (*prefix).to_string(),
            handler: json!(prefix),
            path_from_rest: *path_from_rest,
        })
        .collect()
    }

    /// THE FIXTURE IS THE EQUIVALENCE PROOF, and it runs in CI: every case in
    /// `fixtures/routing-corpus.json` was produced by the SHIPPING `server/routing.mjs`
    /// (`oracle.mjs` drove it), and this replays them here.
    ///
    /// MUTATION: change one character of one case's expected `url` in the fixture.
    /// RESULT:   fails, naming the case and showing both strings.
    #[test]
    fn the_typescript_corpus() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/routing-corpus.json");
        let raw = std::fs::read_to_string(path).expect("the fixture is committed");
        let doc: Value = serde_json::from_str(&raw).expect("the fixture is JSON");
        let table: Vec<Route> = doc["routes"]
            .as_array()
            .expect("a routes array")
            .iter()
            .map(|r| Route {
                prefix: r["prefix"].as_str().unwrap_or("").to_string(),
                handler: r["handler"].clone(),
                path_from_rest: r["pathFromRest"].as_bool().unwrap_or(false),
            })
            .collect();

        let mut hosts = 0usize;
        for case in doc["hosts"].as_array().expect("a hosts array") {
            let headers = case["headers"]
                .as_object()
                .expect("a headers object")
                .clone();
            let want = &case["host"];
            assert_eq!(&resolve_host(&headers), want, "resolveHost({headers:?})");
            hosts += 1;
        }

        let mut routed = 0usize;
        for case in doc["routes_cases"]
            .as_array()
            .expect("a routes_cases array")
        {
            let raw_url = case["rawUrl"].as_str().expect("a rawUrl");
            let got = resolve_route(&table, raw_url);
            match (got, case["hit"].as_object()) {
                (None, None) => {}
                (Some(hit), Some(want)) => {
                    assert_eq!(
                        hit.route.prefix,
                        want["prefix"].as_str().unwrap_or(""),
                        "resolveRoute({raw_url:?}) prefix"
                    );
                    assert_eq!(
                        hit.pathname,
                        want["pathname"].as_str().unwrap_or(""),
                        "pathname"
                    );
                    assert_eq!(hit.search, want["search"].as_str().unwrap_or(""), "search");
                    // And the URL that hit builds, which is what the caller actually sends.
                    let host = &case["host"];
                    assert_eq!(
                        build_url(&hit, host),
                        case["url"].as_str().unwrap_or(""),
                        "buildUrl({raw_url:?}, {host:?})"
                    );
                    routed += 1;
                }
                (got, want) => panic!("resolveRoute({raw_url:?}): got {got:?}, want {want:?}"),
            }
        }
        assert!(hosts >= 8, "the fixture moved: only {hosts} host case(s)");
        assert!(
            routed >= 20,
            "the fixture moved: only {routed} routed case(s)"
        );
    }

    #[test]
    fn the_separator_rule_is_what_keeps_git_and_github_apart() {
        // The JavaScript suite's own words: a naive `startsWith` routes github traffic to the git
        // handler. Both directions are pinned here.
        let table = routes();
        assert_eq!(
            resolve_route(&table, "/api/git").unwrap().route.prefix,
            "/api/git"
        );
        assert_eq!(
            resolve_route(&table, "/api/git/info/refs")
                .unwrap()
                .route
                .prefix,
            "/api/git"
        );
        assert_eq!(
            resolve_route(&table, "/api/github/o/r")
                .unwrap()
                .route
                .prefix,
            "/api/github"
        );
        assert!(resolve_route(&table, "/api/gitx").is_none());
        assert!(resolve_route(&table, "/api/githubx/y").is_none());
    }

    #[test]
    fn a_caller_supplied_path_is_dropped_and_the_rest_are_kept_in_order() {
        let table = routes();
        let hit = resolve_route(
            &table,
            "/api/git/info/refs?path=%2Fevil&service=git-upload-pack&a=1",
        )
        .expect("a hit");
        let url = build_url(&hit, &json!("api.saisi.online"));
        assert_eq!(
            url,
            "https://api.saisi.online/api/git?path=%2Finfo%2Frefs&service=git-upload-pack&a=1"
        );
    }
}
