//! THE VPS RELAY, AS A BINARY — the axum/hyper target block ④ names.
//!
//! WHAT THIS IS AND WHAT IT IS NOT. Every DECISION the shipping JavaScript makes is already in this
//! crate's library, proved against a corpus generated by driving that JavaScript: the routing table, the
//! header plumbing, `/api/proxy`'s CORS and upstream plan, the three content gates, `api/zen`'s target
//! contract and `summrise-relay`'s token. **THIS FILE IS THE WIRING** — an HTTP surface that asks those
//! decisions and carries out the answer — and it is deliberately the smallest thing that can be run.
//!
//! # WHAT IS WIRED, AND WHAT IS NAMED RATHER THAN HALF-DONE
//!
//!   * `/api/proxy` and `/api/zen` — the two API relays: a preflight, a BYOK refusal, an upstream request
//!     built from the plan, and the 5xx rule.
//!   * `/api/git`, `/api/github` and `/api/gform` — the three content handlers — are NOT wired here yet.
//!     Their decisions are in the crate (`parse_route`, `upstream_url`, `redirect_target`, `rewrite_body`,
//!     the redirect caps), and what is missing is the redirect LOOP and the body rewriting at the edge;
//!     naming that is the plan's rule for work that is not done rather than pretending the surface is
//!     complete.
//!
//! # AND THE SMOKE IS THE NODE SUITE
//!
//! The plan says it: this process's smoke is `proxies/api-relay/api/test/*.test.mjs` (73 cases) plus the
//! relay's own (8), because the JavaScript is still the implementation until a cutover. What this file's
//! tests add is that the WIRING answers what the decisions say — a stub upstream on loopback, no TLS, no
//! network.

use std::sync::Arc;

use axum::body::Body;
use axum::extract::State;
use axum::http::{HeaderMap, HeaderName, HeaderValue, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::any;
use axum::Router;
use serde_json::Value;

use summrise_relay::{
    collect_response_headers, cors_headers, proxy_upstream_plan, request_host, zen_upstream_plan,
    ProxyPlan, ZenPlan,
};

/// What the wiring needs that the decisions do not: where to dial, and the origins this relay serves.
#[derive(Clone)]
pub struct Relay {
    /// The client every upstream request goes through. One per process, as the JavaScript's `fetch` is.
    pub client: reqwest::Client,
    /// The console origins the CORS copy allows. Read once at start-up.
    pub allowed_origins: Arc<Vec<String>>,
    /// **THE TEST SEAM, AND THE SAME ONE THE JAVASCRIPT HAS.** The node suite reaches these gates by
    /// replacing `globalThis.fetch` with a stub; a compiled binary cannot be monkey-patched, so the
    /// origin an upstream request is dialled at is a field. `None` in production — the plans own their
    /// URLs — and a loopback stub in the tests, which is what makes an end-to-end test possible without
    /// TLS and without a network.
    pub upstream_origin: Option<String>,
}

impl Relay {
    /// The URL to dial, with the test seam applied when it is set.
    fn dial(&self, url: &str) -> String {
        match &self.upstream_origin {
            Some(base) => match (url::Url::parse(url), url::Url::parse(base)) {
                (Ok(u), Ok(b)) => {
                    let mut out = b;
                    out.set_path(u.path());
                    out.set_query(u.query());
                    out.to_string()
                }
                _ => url.to_string(),
            },
            None => url.to_string(),
        }
    }
}

/// The app, as a value — so a test can drive it in-process and the binary can serve it.
pub fn app(relay: Relay) -> Router {
    Router::new()
        .route("/api/proxy", any(proxy))
        .route("/api/zen", any(zen))
        .with_state(relay)
}

/// The reply headers every handler carries: the CORS copy for this origin and host.
fn cors_for(headers: &HeaderMap, uri: &axum::http::Uri) -> Vec<(String, String)> {
    let origin = headers
        .get("origin")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("");
    let url = format!(
        "http://{}{}",
        headers
            .get("host")
            .and_then(|v| v.to_str().ok())
            .unwrap_or(""),
        uri
    );
    cors_headers(origin, &request_host(&url))
}

/// Turn the plan's `(name, value)` pairs into reply headers, then the CORS copy on top — which is the
/// JavaScript's order (`for (const [k, v] of Object.entries(cors)) rh.set(k, v)`).
fn build_headers(pairs: &[(String, String)], cors: &[(String, String)]) -> HeaderMap {
    let mut out = HeaderMap::new();
    for (k, v) in pairs.iter().chain(cors.iter()) {
        if let (Ok(name), Ok(value)) = (
            HeaderName::from_bytes(k.as_bytes()),
            HeaderValue::from_str(v),
        ) {
            out.insert(name, value);
        }
    }
    out
}

/// A refusal: the JSON body the JavaScript writes, with the CORS copy.
fn refusal(status: u16, error: &str, cors: &[(String, String)]) -> Response {
    let body = serde_json::json!({ "error": error }).to_string();
    let mut headers = build_headers(&[], cors);
    headers.insert("content-type", HeaderValue::from_static("application/json"));
    (
        StatusCode::from_u16(status).unwrap_or(StatusCode::BAD_REQUEST),
        headers,
        body,
    )
        .into_response()
}

/// The headers a request carries, as the plain object the decisions read. Lowercased, because
/// `request.headers.get(name)` is case-insensitive and the plans fold the name themselves.
fn request_headers(headers: &HeaderMap) -> serde_json::Map<String, Value> {
    let mut out = serde_json::Map::new();
    for (name, value) in headers.iter() {
        if let Ok(v) = value.to_str() {
            out.insert(name.as_str().to_string(), Value::String(v.to_string()));
        }
    }
    out
}

async fn proxy(State(relay): State<Relay>, req: axum::extract::Request) -> Response {
    let (parts, body) = req.into_parts();
    let uri = parts.uri.clone();
    let cors = cors_for(&parts.headers, &uri);
    if parts.method == axum::http::Method::OPTIONS {
        return (StatusCode::OK, build_headers(&[], &cors)).into_response();
    }
    let headers = request_headers(&parts.headers);
    let method = parts.method.as_str().to_string();
    match proxy_upstream_plan(&method, &headers) {
        ProxyPlan::Preflight => (StatusCode::OK, build_headers(&[], &cors)).into_response(),
        ProxyPlan::Refused { status, error } => refusal(status, &error, &cors),
        ProxyPlan::Send {
            headers: plan,
            send_body,
        } => {
            let bytes = if send_body {
                axum::body::to_bytes(body, 8 * 1024 * 1024)
                    .await
                    .unwrap_or_default()
            } else {
                Default::default()
            };
            let mut request = relay.client.request(
                reqwest::Method::from_bytes(method.as_bytes()).unwrap_or(reqwest::Method::POST),
                relay.dial("https://openrouter.ai/api/v1/messages"),
            );
            for (k, v) in &plan {
                request = request.header(k, v);
            }
            if send_body {
                request = request.body(bytes.to_vec());
            }
            forward(request, &cors).await
        }
    }
}

async fn zen(State(relay): State<Relay>, req: axum::extract::Request) -> Response {
    let (parts, body) = req.into_parts();
    let uri = parts.uri.clone();
    let cors = cors_for(&parts.headers, &uri);
    if parts.method == axum::http::Method::OPTIONS {
        return (StatusCode::OK, build_headers(&[], &cors)).into_response();
    }
    let headers = request_headers(&parts.headers);
    let method = parts.method.as_str().to_string();
    let url = format!(
        "https://{}{}",
        parts
            .headers
            .get("host")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("relay"),
        uri
    );
    match zen_upstream_plan(&method, &url, &headers) {
        ZenPlan::Preflight => (StatusCode::OK, build_headers(&[], &cors)).into_response(),
        ZenPlan::Refused { status, error } => refusal(status, &error, &cors),
        ZenPlan::Send {
            url,
            headers: plan,
            send_body,
        } => {
            let bytes = if send_body {
                axum::body::to_bytes(body, 8 * 1024 * 1024)
                    .await
                    .unwrap_or_default()
            } else {
                Default::default()
            };
            let mut request = relay.client.request(
                reqwest::Method::from_bytes(method.as_bytes()).unwrap_or(reqwest::Method::POST),
                relay.dial(&url),
            );
            for (k, v) in &plan {
                request = request.header(k, v);
            }
            if send_body {
                request = request.body(bytes.to_vec());
            }
            forward(request, &cors).await
        }
    }
}

/// Send it, and apply the two rules every handler shares: **the 5xx rule** (generic client text, detail
/// stays in the log) and the CORS copy on the reply.
async fn forward(request: reqwest::RequestBuilder, cors: &[(String, String)]) -> Response {
    let response = match request.send().await {
        Ok(r) => r,
        Err(e) => {
            eprintln!("[vrelay] upstream error: {e}");
            return refusal(500, "Internal error", cors);
        }
    };
    let status = response.status().as_u16();
    let entries: Vec<(String, String)> = response
        .headers()
        .iter()
        .filter_map(|(k, v)| {
            v.to_str()
                .ok()
                .map(|v| (k.as_str().to_string(), v.to_string()))
        })
        .collect();
    let set_cookie: Vec<String> = response
        .headers()
        .get_all("set-cookie")
        .iter()
        .filter_map(|v| v.to_str().ok().map(str::to_string))
        .collect();
    if status >= 500 {
        // THE 5xx RULE IS A CONTRACT (`proxies/README.md:13`): the provider's own words about a request it
        // rejected must not leave the worker. The detail goes to the log.
        let detail = response.text().await.unwrap_or_default();
        eprintln!(
            "[vrelay] upstream {status}: {}",
            &detail[..detail.len().min(500)]
        );
        return refusal(status, "Upstream unavailable", cors);
    }
    let plain = collect_response_headers(&entries, &set_cookie);
    let pairs: Vec<(String, String)> = plain
        .as_object()
        .map(|o| {
            o.iter()
                .filter_map(|(k, v)| {
                    v.as_str().map(|s| (k.clone(), s.to_string())).or_else(|| {
                        v.as_array().map(|a| {
                            (
                                k.clone(),
                                a.iter()
                                    .filter_map(|x| x.as_str())
                                    .collect::<Vec<_>>()
                                    .join(", "),
                            )
                        })
                    })
                })
                .collect()
        })
        .unwrap_or_default();
    let body = response.bytes().await.unwrap_or_default();
    (
        StatusCode::from_u16(status).unwrap_or(StatusCode::BAD_GATEWAY),
        build_headers(&pairs, cors),
        Body::from(body),
    )
        .into_response()
}

#[tokio::main]
async fn main() {
    let listen = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "127.0.0.1:8081".to_string());
    let relay = Relay {
        client: reqwest::Client::builder().build().expect("an HTTP client"),
        allowed_origins: Arc::new(vec![
            "https://ai.saisi.online".to_string(),
            "https://api.saisi.online".to_string(),
        ]),
        upstream_origin: None,
    };
    let listener = tokio::net::TcpListener::bind(&listen)
        .await
        .unwrap_or_else(|e| panic!("cannot listen on {listen}: {e}"));
    println!("vrelay listening on {listen}");
    axum::serve(listener, app(relay))
        .await
        .expect("the server runs");
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::to_bytes;
    use axum::http::Request;
    use tower::ServiceExt;

    /// A stub upstream on loopback, WRITTEN AS RAW BYTES — the same thing the node suite gets by
    /// replacing `globalThis.fetch`, and the only way to make an upstream LIE: axum refuses to emit a
    /// `content-length` that disagrees with its own body, which is one of the two lies this relay exists
    /// to strip.
    async fn stub_upstream(status: u16, body: &'static str) -> String {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("a port");
        let addr = listener.local_addr().expect("an address");
        tokio::spawn(async move {
            while let Ok((mut sock, _)) = listener.accept().await {
                tokio::spawn(async move {
                    let mut buf = vec![0u8; 8192];
                    let _ = sock.read(&mut buf).await;
                    let reason = if status == 200 {
                        "OK"
                    } else {
                        "Service Unavailable"
                    };
                    // THE LIE IS `content-encoding: gzip` OVER BYTES THAT ARE NOT COMPRESSED, which is
                    // what `fetch` leaves behind after it decompresses: the length is honest because a
                    // dishonest one would hang the client rather than reach the assertion.
                    let response = format!(
                        "HTTP/1.1 {status} {reason}\r\ncontent-type: application/json\r\nx-stub: yes\r\ncontent-length: {}\r\ncontent-encoding: gzip\r\nconnection: close\r\n\r\n{body}",
                        body.len()
                    );
                    let _ = sock.write_all(response.as_bytes()).await;
                    let _ = sock.shutdown().await;
                });
            }
        });
        format!("http://{addr}")
    }

    fn relay_at(origin: String) -> Relay {
        Relay {
            client: reqwest::Client::new(),
            allowed_origins: Arc::new(Vec::new()),
            upstream_origin: Some(origin),
        }
    }

    async fn call(relay: Relay, request: Request<Body>) -> (StatusCode, HeaderMap, String) {
        let response = app(relay).oneshot(request).await.expect("a response");
        let status = response.status();
        let headers = response.headers().clone();
        let body = to_bytes(response.into_body(), 1024 * 1024)
            .await
            .expect("a body");
        (status, headers, String::from_utf8_lossy(&body).to_string())
    }

    #[tokio::test]
    async fn a_preflight_is_answered_before_the_gate() {
        let relay = relay_at("http://127.0.0.1:1".to_string());
        let (status, headers, _) = call(
            relay,
            Request::builder()
                .method("OPTIONS")
                .uri("/api/proxy")
                .header("origin", "https://ai.saisi.online")
                .header("host", "v.saisi.online")
                .body(Body::empty())
                .unwrap(),
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        assert_eq!(
            headers
                .get("access-control-allow-origin")
                .and_then(|v| v.to_str().ok()),
            Some("https://ai.saisi.online")
        );
        assert!(headers.get("vary").is_some(), "the reply varies on Origin");
    }

    #[tokio::test]
    async fn a_caller_with_no_key_is_refused_and_never_dials() {
        // The origin points at a port nothing listens on: if this test dialled, it would fail with a
        // connection error rather than a 401, which is what makes "never dials" an assertion.
        let relay = relay_at("http://127.0.0.1:1".to_string());
        let (status, headers, body) = call(
            relay,
            Request::builder()
                .method("POST")
                .uri("/api/proxy")
                .header("host", "v.saisi.online")
                .body(Body::from("{}"))
                .unwrap(),
        )
        .await;
        assert_eq!(status, StatusCode::UNAUTHORIZED);
        assert!(body.contains("BYOK"), "{body}");
        assert_eq!(
            headers.get("content-type").and_then(|v| v.to_str().ok()),
            Some("application/json")
        );
    }

    #[tokio::test]
    async fn a_happy_path_reaches_the_upstream_and_comes_back() {
        let origin = stub_upstream(200, r#"{"ok":true}"#).await;
        let (status, headers, body) = call(
            relay_at(origin),
            Request::builder()
                .method("POST")
                .uri("/api/proxy")
                .header("host", "v.saisi.online")
                .header("authorization", "Bearer sk-test")
                .body(Body::from(r#"{"x":1}"#))
                .unwrap(),
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        assert_eq!(body, r#"{"ok":true}"#);
        // **THE UPSTREAM'S `content-encoding` IS NOT FORWARDED.** The stub claimed `gzip` over bytes it
        // never compressed — exactly what `fetch` leaves behind after decompressing — and forwarding it
        // would make the reply a lie the client acts on. (`content-length` is stripped by the same rule;
        // an upstream that lies about IT cannot be provoked here, because the client would wait for bytes
        // that never come — which is the reason the rule exists rather than a gap in the test.)
        assert!(
            headers.get("content-encoding").is_none(),
            "a gzip claim over decompressed bytes must not ride through"
        );
        assert_eq!(
            headers.get("x-stub").and_then(|v| v.to_str().ok()),
            Some("yes"),
            "and the allowlisted headers still do"
        );
    }

    #[tokio::test]
    async fn a_five_hundred_is_generic_client_text_and_the_detail_stays_in_the_log() {
        let origin = stub_upstream(503, "UPSTREAM SECRET DETAIL").await;
        let (status, _, body) = call(
            relay_at(origin),
            Request::builder()
                .method("POST")
                .uri("/api/proxy")
                .header("host", "v.saisi.online")
                .header("authorization", "Bearer sk-test")
                .body(Body::from("{}"))
                .unwrap(),
        )
        .await;
        assert_eq!(status, StatusCode::SERVICE_UNAVAILABLE);
        assert!(body.contains("Upstream unavailable"), "{body}");
        assert!(
            !body.contains("SECRET"),
            "the provider's words must not leave the worker: {body}"
        );
    }

    #[tokio::test]
    async fn the_zen_target_contract_survives_the_wiring() {
        let origin = stub_upstream(200, "{}").await;
        let relay = relay_at(origin);
        // An absent target is `og` — a documented default.
        let (status, _, _) = call(
            relay.clone(),
            Request::builder()
                .method("POST")
                .uri("/api/zen?path=%2Fv1%2Fmessages")
                .header("host", "v.saisi.online")
                .header("x-api-key", "sk-test")
                .body(Body::from("{}"))
                .unwrap(),
        )
        .await;
        assert_eq!(status, StatusCode::OK);
        // An UNLISTED target is refused, and never dialled.
        let (status, _, body) = call(
            relay,
            Request::builder()
                .method("POST")
                .uri("/api/zen?target=nope&path=%2Fv1%2Fmessages")
                .header("host", "v.saisi.online")
                .header("x-api-key", "sk-test")
                .body(Body::from("{}"))
                .unwrap(),
        )
        .await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert!(body.contains("unknown target"), "{body}");
    }
}
